class PopulateOrderTypes < ActiveRecord::Migration
  def up
  	 OrderType.create description: "5-HIAA, QUANTATIVE"
	 OrderType.create description: "5-NUCLEOTIDASE"
	 OrderType.create description: "8 METHOXYPSORALENE"
	 OrderType.create description: "8-MOP"
	 OrderType.create description: "11-DEOXYCORTISOL"
	 OrderType.create description: "17-KETOGENIC STEROIDS"
	 OrderType.create description: "17-KETOSTEROIDS"
	 OrderType.create description: "17- OH CORTICOSTEROID"
	 OrderType.create description: "17-OH PROGESTERONE"
	 OrderType.create description: "ACETAMINOPHEN"
	 OrderType.create description: "ACETONE, QUALITATIVE"
	 OrderType.create description: "ACETYL RECEPTOR BIND AB"
	 OrderType.create description: "ACETYL RECEPTOR BLOCK AB"
	 OrderType.create description: "ACETYL RECEPTOR; MODULATING AB"
	 OrderType.create description: "ACID FAST BACILLUS CULTURE AND STAIN"
	 OrderType.create description: "ACTH"
	 OrderType.create description: "ACUTE HEPATITIS PANEL HEPATITS A AB IGM; HEPATITIS B CORE AB IGM; HEPATITIS B SURFACE AG; HEPATITIS C AB"
	 OrderType.create description: "ADENOVIRUS CF"
	 OrderType.create description: "ADRENAL AB"
	 OrderType.create description: "ADRENOCORTICOTROPIC HORMONE (ACTH)"
	 OrderType.create description: "AF BILIRUBIN; DELTA OD; UNCONJUGATED BILIRUBIN"
	 OrderType.create description: "AFB BLOOD CULTURE"
	 OrderType.create description: "AFP AMNIOTIC FLUID"
	 OrderType.create description: "AFP MATERNAL"
	 OrderType.create description: "AFP PLUS"
	 OrderType.create description: "AFP MS4 (QUAD)"
	 OrderType.create description: "AFP, TUMOR MARKER"
	 OrderType.create description: "ALBUMIN"
	 OrderType.create description: "ALBUMIN, BODY FLUID"
	 OrderType.create description: "ALCOHOL"
	 OrderType.create description: "ALDOLASE"
	 OrderType.create description: "ALDOSTERONE"
	 OrderType.create description: "ALDOSTERONE, URINE"
	 OrderType.create description: "TEST"
	 OrderType.create description: "ALKALINE PHOSPHATASE"
	 OrderType.create description: "ALKALINE PHOSPHATASE ISOENZYME"
	 OrderType.create description: "ALPHA FETOPROTEIN AMNIOTIC FLUID"
	 OrderType.create description: "ALPHA FETOPROTEIN MATERNAL"
	 OrderType.create description: "ALPHA FETO PROTEIN PLUS"
	 OrderType.create description: "ALPHA FETOPROTEIN; TUMOR MARKER"
	 OrderType.create description: "ALPHA-1 ANTITRYPSIN"
	 OrderType.create description: "ALPHA-1 ANTITRYPSIN, FECAL"
	 OrderType.create description: "ALT (SGPT)"
	 OrderType.create description: "ALUMINUM"
	 OrderType.create description: "ALUMINUM, UIRNE"
	 OrderType.create description: "AMIKACIN"
	 OrderType.create description: "AMINO ACID QUAL SCREEN"
	 OrderType.create description: "AMINO ACID QUAL SCREEN, UR"
	 OrderType.create description: "AMINO ACID QUANT PLASMA"
	 OrderType.create description: "AMINO ACID QUANT, UR"
	 OrderType.create description: "AMINO ACIDS, CSF"
	 OrderType.create description: "AMINOLEVULINIC ACID"
	 OrderType.create description: "AMIODARONE"
	 OrderType.create description: "AMITRIPTYLINE/NORTRIPTYLINE"
	 OrderType.create description: "AMMONIA"
	 OrderType.create description: "AMOEBIASIS"
	 OrderType.create description: "AMOXAPINE (ASCENDIN)"
	 OrderType.create description: "AMYLASE"
	 OrderType.create description: "AMYLASE, BODY FLUID"
	 OrderType.create description: "AMYLASE, URINE - TIMED"
	 OrderType.create description: "AMYLASE ISOENZYMES; PANCREATIC, SALIVARY, TOTAL AMYLASE"
	 OrderType.create description: "AMYLASE, URINE - RANDOM"
	 OrderType.create description: "ANA SCREEN"
	 OrderType.create description: "ANA PROFILE;  SMITH, RNP / SMITH, SCL-70, SSA, SSB, JO-1, dsDNA"
	 OrderType.create description: "ANA BY IFA"
	 OrderType.create description: "ANAEROBIC CULTURE"
	 OrderType.create description: "ANCA PANEL"
	 OrderType.create description: "ANDROSTANEDIONE"
	 OrderType.create description: "ANGIOTENSIN CONVERTING ENZYME (ACE)"
	 OrderType.create description: "ANGIOTENSIN CONVERTING ENZYME,CSF"
	 OrderType.create description: "TEST"
	 OrderType.create description: "ANTENATAL RH NEG WORK UP; ABO, INDIRECT ANTIGLOBULIN, RH"
	 OrderType.create description: "ANTIBODY TITER"
	 OrderType.create description: "ANTICARDIOLIPIN; IGM, IGG, IGA"
	 OrderType.create description: "ANTINEUTROPHIL CYTO AB; (ANCA PANEL)"
	 OrderType.create description: "ANTINUCLEAR AB; (ANA ACREEN)"
	 OrderType.create description: "ANTISTREPTOLYSIN O"
	 OrderType.create description: "ANTITHROMBIN III"
	 OrderType.create description: "APC RESISTANCE PROFILE;  APC PTT BASED RESIST, APC PTT RATIO, APC PT BASED RESIS"
	 OrderType.create description: "APOLIPOPROTEIN A1"
	 OrderType.create description: "APOLIPOPROTEIN B-100"
	 OrderType.create description: "APOLIPOPROTEIN E BY PCR"
	 OrderType.create description: "APT TEST"
	 OrderType.create description: "ARBOVIRUS PANEL IGM; CALIFORNIA ENCEPHALITIS, EAST EQUINE ENCEPHALITIS, ST.LOUIS ENCEPHALITIS, WESTERN ENCEPHALITIS"
	 OrderType.create description: "ARBOVIRUS PANEL IGG; CALIFORNIA ENCEPHALITIS, EAST EQUINE ENCEPHALITIS, ST.LOUIS ENCEPHALITIS, WESTERN ENCEPHALITIS"
	 OrderType.create description: "ARGININE VASOPRESSIN HORMONE"
	 OrderType.create description: "ARIZONA ALLERGY, IGE;  RAGWEED, MUG WORT, ENG PLANT, LAMB QTR, RUSSIAN THISTLE, BERMUDA, RYE PERENNIAL, TIMOTHY, JUNE GRASS, JOHNSON GRASS, CEDAR, MOUNTAIN ELM, OAK, COTTONWOOD, MESQUITE, OLIVE TREE, PENICILLIN, HOMODENDRON, FUMAGATIS, ALTERNARIA, D.PTERNYSSINUS, D.FARINAE, CAT EPITHELIAL, DOG EPITHELIAL, HORSE HAIR, COW HAIR, HOUSE DUST"
	 OrderType.create description: "ARSENIC, BLOOD"
	 OrderType.create description: "ARSENIC, URINE"
	 OrderType.create description: "ARTHRITIS PANEL; URIC ACID, SED RATE, ANA SCREEN, RHEUMATOID FACTOR"
	 OrderType.create description: "ARYLSULFATASE A, URINE"
	 OrderType.create description: "ASO (STREPTOLYSIN O AB)"
	 OrderType.create description: "ASPERGILLUS ANTIBODY CF"
	 OrderType.create description: "ASPERGILLUS ID"
	 OrderType.create description: "ASPIRIN RESISTANCE"
	 OrderType.create description: "AST (SGOT)"
	 OrderType.create description: "ATRIAL NUTRIURETIC FACTOR"
	 OrderType.create description: "AUTOPSY"
	 OrderType.create description: "VITAMIN B-12"
	 OrderType.create description: "TEST"
	 OrderType.create description: "BARBITURATES"
	 OrderType.create description: "BASIC METBOLIC PANEL; BUN, CREATININE, ELECTROLYTES, GLUCOSE, CALCIUM"
	 OrderType.create description: "BCR ANALYSIS"
	 OrderType.create description: "BCR ANALYSIS"
	 OrderType.create description: "BENCE-JONES PROTEIN,PROTEIN"
	 OrderType.create description: "BETA - CAROTENE"
	 OrderType.create description: "BETA - GLUCURONIDASE"
	 OrderType.create description: "BETA - HCG, QUALITATIVE AND QUANTITATIVE"
	 OrderType.create description: "BETA - HYDROXYBUTYRIC ACID"
	 OrderType.create description: "BETA -2 - MICROGLOBULINS"
	 OrderType.create description: "B2 TRANSFERRIN"
	 OrderType.create description: "BETHESDA ASSAY QUANT"
	 OrderType.create description: "BILE ACIDS, FRACTIONATED; DIHYDROXY, TRIHYDROXY"
	 OrderType.create description: "BILIRUBIN; NEONATAL; BILIRUBIN-TOTAL, BILIRUBIN-CONJUGATED"
	 OrderType.create description: "BILIRUBIN, BODY FLUID"
	 OrderType.create description: "BILIRUBIN; TOTAL AND DIRECT"
	 OrderType.create description: "BLASTOMYCES ANTIBODY, CF"
	 OrderType.create description: "BLASTOMYCES ID"
	 OrderType.create description: "BLEEDING TIME - ROUTINE"
	 OrderType.create description: "BLEEDING TIME - SURGICUTT"
	 OrderType.create description: "BLOOD CULTURE"
	 OrderType.create description: "BLOOD TYPE - ABO AND RH"
	 OrderType.create description: "BLOOD TYPE AND RH - CORD"
	 OrderType.create description: "BNP"
	 OrderType.create description: "BODY FLD CULT + GRAM + ANAEROBE"
	 OrderType.create description: "BONE GLA PROTEIN"
	 OrderType.create description: "BONE MARROW ASP"
	 OrderType.create description: "BONE MARROW - STAIN"
	 OrderType.create description: "BORRELIA - LYME AB"
	 OrderType.create description: "BORRELIA HERMSII AB"
	 OrderType.create description: "BOTULISM"
	 OrderType.create description: "BREAST FLUID - CYTOLOGY"
	 OrderType.create description: "BROMIDE"
	 OrderType.create description: "TEST"
	 OrderType.create description: "BRONCHIAL BRUSH - CYTOLOGY"
	 OrderType.create description: "BRONCHIAL WASH - CYTOLOGY"
	 OrderType.create description: "BRUCELLA BATTERY;   B.ABORTUS, B.MELETENSIS, B.SUIS"
	 OrderType.create description: "BUCCAL SMEAR - CYTOLOGY"
	 OrderType.create description: "BUN"
	 OrderType.create description: "C-1 - ESTERASE INHIBITOR"
	 OrderType.create description: "C1Q BINDING ASSAY"
	 OrderType.create description: "C - 3 COMPLEMENT"
	 OrderType.create description: "C3,C4 COMPLEMENT"
	 OrderType.create description: "C - 4 COMPLEMENT"
	 OrderType.create description: "C - PEPTIDE, SERUM"
	 OrderType.create description: "C - REACTIVE PROTEIN, HIGHLY SENSITIVE"
	 OrderType.create description: "CA 125"
	 OrderType.create description: "CA 19-9"
	 OrderType.create description: "CA 27.29"
	 OrderType.create description: "CA15-3 (CA 27-29)"
	 OrderType.create description: "CADMIUM, BLOOD"
	 OrderType.create description: "CADMIUM, URINE"
	 OrderType.create description: "CAFFEINE"
	 OrderType.create description: "CALCIFEDIOL"
	 OrderType.create description: "CALCITONIN"
	 OrderType.create description: "CALCIUM"
	 OrderType.create description: "CALCIUM, IONIZED"
	 OrderType.create description: "CALCIUM, 24 HR URINE"
	 OrderType.create description: "CALCIUM, RANDOM URINE"
	 OrderType.create description: "CANCER ANTIGEN BREAST; (CA 15-3), (CA 27,29)"
	 OrderType.create description: "CANCER ANTIGEN - GI; (CA 19-9)"
	 OrderType.create description: "CANCER ANTIGEN - 125; (CA 125)"
	 OrderType.create description: "CANDIDA ANTIBODY (ID)"
	 OrderType.create description: "CANNABINOIDS, SERUM"
	 OrderType.create description: "CARBAMAZEPINE (TEGRETOL)"
	 OrderType.create description: "CARBAMAZEPINE EPOXIDE"
	 OrderType.create description: "CARBAMAZEPINE, FREE"
	 OrderType.create description: "CARBON DIOXIDE (CO2)"
	 OrderType.create description: "CARCINOEMBRYONIC ANTEGEN (CEA)"
	 OrderType.create description: "CARDIOLIPIN AB IGG/IGM/IGE"
	 OrderType.create description: "TEST"
	 OrderType.create description: "CARNITINE FREE AND TOTAL"
	 OrderType.create description: "CARNITINE FREE"
	 OrderType.create description: "CATECHOLAMINES QUANT; EPINEPHRINE, NOREPINEPHRINE"
	 OrderType.create description: "CATHETER TIP CULTURE"
	 OrderType.create description: "CBC WITH DIFFERENTIAL AND PLATELETS; HEMATOCRIT, HEMOGLOBIN, MCH, MCV, MCHC, RDW, RBC, WBC, POLYS "
	 OrderType.create description: "CD 4 / 8 LYMPHOCYTE PHENOTYPING"
	 OrderType.create description: "CEA (CARCINOEMBRYONIC AG)"
	 OrderType.create description: "CELL BLOCK"
	 OrderType.create description: "CELL COUNT, BODY FLUID"
	 OrderType.create description: "CELL COUNT, CSF"
	 OrderType.create description: "CELONTIN"
	 OrderType.create description: "CERULOPLASMIN"
	 OrderType.create description: "CERVICAL/VAGINAL SMEAR"
	 OrderType.create description: "CH50 COMPLEMENT"
	 OrderType.create description: "CHLAMYDIA AB IGG"
	 OrderType.create description: "CHLAMYDIA AB IGM"
	 OrderType.create description: "CHLAMYDIA BY DFA"
	 OrderType.create description: "CHLAMYDIA BY DNA PROBE"
	 OrderType.create description: "CHLAMYDIA BY APTIMA MEDIA"
	 OrderType.create description: "CHLAMYDIA BY LCR"
	 OrderType.create description: "CHLAMYDIA CULTURE"
	 OrderType.create description: "CHLORIDE, BODY FLUID"
	 OrderType.create description: "CHLORIDE, CSF"
	 OrderType.create description: "CHLORIDE, NASAL SECRETIONS"
	 OrderType.create description: "CHLORIDE, SERUM"
	 OrderType.create description: "CHLORIDE, 24 HR URINE"
	 OrderType.create description: "CHLORIDE, RANDOM URINE"
	 OrderType.create description: "CHLORPROMAZINE"
	 OrderType.create description: "CHOLESTEROL"
	 OrderType.create description: "CHOLINESTERASE; RBC"
	 OrderType.create description: "CHROMOSOME AMNIOTIC FLUID"
	 OrderType.create description: "TEST"
	 OrderType.create description: "CHROMOSOME ANALYSIS, BLOOD"
	 OrderType.create description: "CHROMOSOME ANALYSIS, EXTENDED BANDING (HIGH RESOLUTION)"
	 OrderType.create description: "CHROMOSOME BONE MARROW"
	 OrderType.create description: "CHROMOSOME CHORIONIC VILLI"
	 OrderType.create description: "CHROMOSOME FISH; FISH FOR ANY TEST NOT LISTED UNDER MCD"
	 OrderType.create description: "CHROMOSOME MCD; FISH FOR DIGEORGE, VCF, CRI-DU-CHAT, WILLIAMS, ANGELMAN'S, MILLER DIEKER, SMITH MAGENIS, AND PRADER-WILLI"
	 OrderType.create description: "CHROMOSOME MOSIAC"
	 OrderType.create description: "CHROMOSOME PRODUCT OF CONCEPTION"
	 OrderType.create description: "CIDAL, SERUM (SCHLICTER TEST)"
	 OrderType.create description: "CLONAZEPAM (CLONOPIN)"
	 OrderType.create description: "CLONOPIN"
	 OrderType.create description: "CLORZEPATE ASSAYED AS NORDIAZEPAM"
	 OrderType.create description: "CLOSTRIDIUM DIFFICILE TOXIN"
	 OrderType.create description: "CMV AB (IGG AND/OR IGM)"
	 OrderType.create description: "CMV AB TOTAL"
	 OrderType.create description: "CMV AB, IGG"
	 OrderType.create description: "CMV AB, IGM"
	 OrderType.create description: "CMV BY PCR"
	 OrderType.create description: "CMV CULTURE, BUFFY COAT CULTURE"
	 OrderType.create description: "CMV CULTURE, URINE"
	 OrderType.create description: "CMV - IGG"
	 OrderType.create description: "CMV - IGM"
	 OrderType.create description: "COCCI - CF -   CSF"
	 OrderType.create description: "COCCI - CF - PAPA"
	 OrderType.create description: "COCCI SEROLOGY (CF / ID)"
	 OrderType.create description: "COCCIDIODES - EIA SERUM"
	 OrderType.create description: "COLONY CT"
	 OrderType.create description: "COLD AGGLUTININ"
	 OrderType.create description: "COLONIC BRUSH - CYTOLOGY"
	 OrderType.create description: "COLORADO TICK FEVER"
	 OrderType.create description: "COMPLEMENT; C-3 AND C-4"
	 OrderType.create description: "COMPLEMENT - CH-50 (RECOMMENDATIONS ARE TO ONLY RUN CH50, CH100 IS STILL AVAILABLE)"
	 OrderType.create description: "COMPREHENSIVE DRUG SCREEN; AMPHETAMINES, ANALGESICS, ANTIDEPRESSANTS, ANTIHISTAMINES, BARBITUATES, BENSODIAZEPINES, CARDIACS, MISC AGENTS, NARCOTICS, PHENOTHIAZINES, SEDATIVES AND HYPNOTICS, VOLATILES"
	 OrderType.create description: "TEST"
	 OrderType.create description: "COMPREHENSIVE METABOLIC PANEL   (CMP); ALBUMIN, ALKALINE PHOSPHATASE (ALP), AST (SGOT), ALT (SGPT), BILIRUBIN (TOTAL), BUN, CALCIUM, CO2, CHLORIDE, CREATININE, POTASSIUM, SODIUM, TOTAL PROTEIN"
	 OrderType.create description: "COPPER, SERUM"
	 OrderType.create description: "COPPER, URINE"
	 OrderType.create description: "CORD BLOOD;  ABO, DIRECT ANTIGLOBULIN, RH"
	 OrderType.create description: "CORTISOL"
	 OrderType.create description: "CORTISOL, URINE"
	 OrderType.create description: "CORTISOL, FREE - URINE"
	 OrderType.create description: "COXSACKIE A; SEROTYPES 7,9,10,16"
	 OrderType.create description: "COXSACKIE B; SEROTYPES 1,2,3,4,5,6"
	 OrderType.create description: "C-PEPTIDE (SERUM)"
	 OrderType.create description: "CPK"
	 OrderType.create description: "CPK/CK-MB ISOENZYME"
	 OrderType.create description: "CREATINE"
	 OrderType.create description: "CREATINE, URINE"
	 OrderType.create description: "CREATININE"
	 OrderType.create description: "CREATININE, CLEARANCE"
	 OrderType.create description: "CREATININE, RANDOM"
	 OrderType.create description: "CREATININE, URINE - 24 HOUR"
	 OrderType.create description: "CROSSMATCH"
	 OrderType.create description: "CRP, HIGHLY SENSITIVE"
	 OrderType.create description: "CRYOGLOBULIN"
	 OrderType.create description: "CRYPTOCOCCUS AG, BLOOD"
	 OrderType.create description: "CRYPTOCOCCUS AG, CSF"
	 OrderType.create description: "CRYPTOSPORIDIA / GIARDIA"
	 OrderType.create description: "CSF - CYTOLOGY"
	 OrderType.create description: "CSF FUNGUS CULTURE +  INDIA INK"
	 OrderType.create description: "CSF CULTURE + GRAM"
	 OrderType.create description: "CULTURE - BONE BANK"
	 OrderType.create description: "CULTURE - TRANS RX"
	 OrderType.create description: "CYANIDE (NOT FOR NITROPRUSSIDE MONITORING)"
	 OrderType.create description: "CYCLIC AMP, NEPHROGENOUS"
	 OrderType.create description: "CYCLIC AMP, PLASMA"
	 OrderType.create description: "CYCLIC AMP URINE"
	 OrderType.create description: "TEST"
	 OrderType.create description: "CYCLOSPORIN"
	 OrderType.create description: "CYCLOSPORIN BY HPLC"
	 OrderType.create description: "CYLEX - IMMUNO"
	 OrderType.create description: "CYSTIC FLUID - CYTOLOGY"
	 OrderType.create description: "CYSTICEROSIS , BLOOD"
	 OrderType.create description: "CYSTICEROSIS , CSF"
	 OrderType.create description: "CYSTINE PLASMA QUANT"
	 OrderType.create description: "CYSTINE URINE QUANT"
	 OrderType.create description: "CYTOGENETICS TESTING (LIST FOLLOWS) CHR AF"
	 OrderType.create description: "CHR BL CHR EB"
	 OrderType.create description: "CHR MOS"
	 OrderType.create description: "CHR CVS CHR POC"
	 OrderType.create description: "CHR ST CHR BM"
	 OrderType.create description: "CHR LB"
	 OrderType.create description: "CHR LN"
	 OrderType.create description: "CHR TC SKN; OSTEOGENESIS IMPERFECTA OR PYRUVATE DEFICIENCY"
	 OrderType.create description: "CHR MCD CHR FISH"
	 OrderType.create description: "CYTOLOGY FOR ACCUR"
	 OrderType.create description: "CYTOMEGALIC INCLUSION BODIES"
	 OrderType.create description: "CYTOMEGALOVIRUS AB TOTAL"
	 OrderType.create description: "CYTOMEGALOVIRUS BY PCR"
	 OrderType.create description: "CYTOMEGALOVIRUS IGG"
	 OrderType.create description: "CYTOMEGALOVIRUS IGG AND/OR IGM"
	 OrderType.create description: "CYTOMEGALOVIRUS IGM"
	 OrderType.create description: "D-DIMER"
	 OrderType.create description: "DEHYDROEPIANDROSTERONE SULFATE (DHEA, SULFATE)"
	 OrderType.create description: "DEHYDROEPIANDROSTERONE (DHEA)"
	 OrderType.create description: "DEHYDROEPIANDROSTERONE (DHEA, URINE)"
	 OrderType.create description: "DELTA OD"
	 OrderType.create description: "DENGUE FEVER"
	 OrderType.create description: "11 - DEOXYCORTISOL"
	 OrderType.create description: "TEST"
	 OrderType.create description: "DEPEKENE (VALPROIC ACID)"
	 OrderType.create description: "DESIPRAMINE`"
	 OrderType.create description: "DHEA"
	 OrderType.create description: "DHEA SULFATE"
	 OrderType.create description: "DIAMOX (ACETAZOLAMIDE)"
	 OrderType.create description: "DIC SCREEN; PT, PTT; HEMOGRAM; FIBRIN SPLIT PRODUCTS"
	 OrderType.create description: "DIGITOXIN"
	 OrderType.create description: "DIGOXIN"
	 OrderType.create description: "5 - a - DIHYDROTESTOSTERONE"
	 OrderType.create description: "DILANTIN (PHENYTOIN)"
	 OrderType.create description: "DIPHTHERIA/TETANUS AB"
	 OrderType.create description: "DIRECT COOMBS - ANTIGLOBULIN"
	 OrderType.create description: "DISOPYRAMINE (NORPACE)"
	 OrderType.create description: "DNA AB QUANT"
	 OrderType.create description: "DNA APOLIPOPROTEIN E"
	 OrderType.create description: "DNA DUCHENNE-MUSCULAR DYSTROPHY"
	 OrderType.create description: "DNA FACTOR V (LEIDENS)"
	 OrderType.create description: "DNA FRAGILE X"
	 OrderType.create description: "DNA HIV-1 QUANT"
	 OrderType.create description: "DNA HUNTINGTONS"
	 OrderType.create description: "DNA KENNEDY DISEASE"
	 OrderType.create description: "DNA MELAS/MITOCHON"
	 OrderType.create description: "DNA MYOTONIC DYSTROPHY"
	 OrderType.create description: "DNA PROTHROMBIN G202IDA GENE"
	 OrderType.create description: "DNASE-B AB"
	 OrderType.create description: "DRUG ABUSE PANEL - STAT URINE; AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, COCAINE METABOLITE, MARIJUANA, OPIATES, PHENCYLIDINE, TRICYCLIC ANTEDEPRESSANTS"
	 OrderType.create description: "DRUG PANEL - 7 NEWBORN MECONIUM; AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE 150, OPIATES, PHENCYCLIDINE"
	 OrderType.create description: "DRUG PANEL - 7 URINE; AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE 150, OPIATES, PHENCYCLIDINE"
	 OrderType.create description: "DRUG PANEL - 7A  URINE; ALCOHOL, AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE 150, OPIATES, PHENCYCLIDINE"
	 OrderType.create description: "DRUG PANEL - 9A  URINE  TRAUMA OR OTHER; ALCOHOL, AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE"
	 OrderType.create description: "300, OPIATES, PHENCYCLIDINE, PROPOXYPHENE"
	 OrderType.create description: "TEST"
	 OrderType.create description: "DRUG SCREEN BLOOD AND URINE; AMPHETAMINES-URINE, BARBITUATES-URINE, BENZODIAZEPINES-URINE, CANNABINOIDS(THC)- URINE,                 COCAINE-URINE, OPIATES-URINE, PHENCYCLIDINE-URINE, TRICYCLICS-URINE, ACETOMENOPHEN-SERUM, SALICYLATES-SERUM, ALCOHOL-SERUM"
	 OrderType.create description: "DUODENAL SECRETIONS - CYTOLOGY"
	 OrderType.create description: "EBV AB"
	 OrderType.create description: "ECHINOCOCCUS SERO"
	 OrderType.create description: "ECHOVIRUS SERO"
	 OrderType.create description: "ELAVIL (AMITRIPTYLINE)"
	 OrderType.create description: "ELECTROLYTES;  CO2, CHLORIDE, POTASSIUM, SODIUM"
	 OrderType.create description: "ELECTROLYTES - FLUID; CHLORIDE-FLUID, POTASSIUM-FLUID, SODIUM-FLUID"
	 OrderType.create description: "ELECTROLYTES - RANDOM URINE; CHLORIDE- RANDOM; POTASSIUM-RANDOM; SODIUM-RANDOM"
	 OrderType.create description: "ELECTROLYTES - 24 HOUR URINE; CHLORIDE-24"
	 OrderType.create description: "HOUR; POTASSIUM-24 HOUR; SODIUM-24 HOUR"
	 OrderType.create description: "ELECTRON MICROSCOPY"
	 OrderType.create description: "ELECTROPHORESIS, PROTEIN; 24 HOUR URINE"
	 OrderType.create description: "ELECTROPHORESIS, PROTEIN - SERUM; ALBUMIN, ALPHA-1, ALPHA-2, BETA, GAMMA"
	 OrderType.create description: "ELECTROPHORESIS, RANDOM URINE"
	 OrderType.create description: "ELECTROPHORESIS, 24 HOUR URINE"
	 OrderType.create description: "ELUTION, WITH ANTIBODY IDENTIFICATION"
	 OrderType.create description: "ENCEPHALITIS AB PANEL; CALIFORNIA ENCEPHALITIS, EAST EQUINE ENCEPHALITIS, ST.LOIUS ENCEPHALITIS, WESTERN ENCEPHALITIS"
	 OrderType.create description: "ENDOMETRIAL ASPIRATE - CYTOLOGY"
	 OrderType.create description: "ENDOMYSIAL AB, IGA"
	 OrderType.create description: "EOSINOPHIL COUNT, ABSOLUTE"
	 OrderType.create description: "EPIDERMAL (SKIN) AB"
	 OrderType.create description: "EPINEPHERINE"
	 OrderType.create description: "EPSTEIN-BARR VIRUS PANEL;  ANTIEARLY AG, ANTINUCLEAR AG, ANTI VCA-IGG, ANTI VCA-IGM"
	 OrderType.create description: "ERYTHROPOIETIN"
	 OrderType.create description: "ESOPHAGEAL BRUSH - CYTOLOGY"
	 OrderType.create description: "ESR (SEDIMENTATION RATE)"
	 OrderType.create description: "ESTERASE STAIN, SPECIFIC"
	 OrderType.create description: "ESTRADIOL - SERUM"
	 OrderType.create description: "ESTRADIOL -  URINE"
	 OrderType.create description: "ESTROGEN RECEPTORS"
	 OrderType.create description: "ESTROGEN URINE FRACTIONATED"
	 OrderType.create description: "TEST"
	 OrderType.create description: "ESTRONE, SERUM"
	 OrderType.create description: "ESTRONE, URINE"
	 OrderType.create description: "ETHOSUXIMIDE"
	 OrderType.create description: "ETHYLENE GLYCOL"
	 OrderType.create description: "EUGLOBULIN LYSIS TIME"
	 OrderType.create description: "FACTOR (2) II (PROTHROMBIN)"
	 OrderType.create description: "FACTOR 2 BY PCR"
	 OrderType.create description: "FACTOR (5) V ASSAY"
	 OrderType.create description: "FACTOR (5) V LEIDEN BY PCR"
	 OrderType.create description: "FACTOR (7) VII ASSAY"
	 OrderType.create description: "FACTOR (8) VIII ASSAY"
	 OrderType.create description: "FACTOR (8) VIII:C"
	 OrderType.create description: "FACTOR (9) IX ASSAY"
	 OrderType.create description: "FACTOR (10) X ASSAY"
	 OrderType.create description: "FACTOR (11) XI"
	 OrderType.create description: "FACTOR (12) XII"
	 OrderType.create description: "FACTOR (13) XIII"
	 OrderType.create description: "FAT STAIN - STOOL  (QUALITATIVE)"
	 OrderType.create description: "FAT STOOL (QUANT)"
	 OrderType.create description: "FATTY ACIDS, FREE"
	 OrderType.create description: "FDP"
	 OrderType.create description: "FEBRILE AGGLUTINATIONS; BRUCELLA; PARATYPHOID A,B,C; PROTEUS OX K,2,19; SALMONELLA A,B,C,E; TULAREMIA; TYPHOID O"
	 OrderType.create description: "FELBAMATE"
	 OrderType.create description: "FERRITIN"
	 OrderType.create description: "FETAL FIBRONECTIN"
	 OrderType.create description: "FETAL HEMOGLOBIN"
	 OrderType.create description: "FETAL RBC - STAIN (KBS)"
	 OrderType.create description: "FETAL SCREEN - RHIG"
	 OrderType.create description: "FIBRIN DEGREDATION PRODUCTS     (FDP)"
	 OrderType.create description: "FIBRINOGEN"
	 OrderType.create description: "FINE NEEDLE ASPIRATION"
	 OrderType.create description: "FK506   (TACROLIMUS)"
	 OrderType.create description: "FLUID CELL COUNT"
	 OrderType.create description: "FLECAINIDE"
	 OrderType.create description: "FLUOXETINE (PROZAC)"
	 OrderType.create description: "TEST"
	 OrderType.create description: "FLUPHENAZINE"
	 OrderType.create description: "FOLATE"
	 OrderType.create description: "FOLATE; RBC"
	 OrderType.create description: "FOSPHENYTOIN"
	 OrderType.create description: "FREE DILANTIN;  %FREE DILANTIN; TOTAL DILANTIN"
	 OrderType.create description: "FREE ERYTHROCYTE PORPH"
	 OrderType.create description: "FREE T3"
	 OrderType.create description: "FREE T4"
	 OrderType.create description: "FREE TEGRETOL"
	 OrderType.create description: "FROZEN SECTION"
	 OrderType.create description: "FSH - SERUM"
	 OrderType.create description: "FSH -  URINE"
	 OrderType.create description: "FSP"
	 OrderType.create description: "FTA MHA/TP- SERUM"
	 OrderType.create description: "FTA MHA/TP-CSF"
	 OrderType.create description: "FUNGAL BLOOD CULTURE"
	 OrderType.create description: "FUNGUS CULTURE"
	 OrderType.create description: "FUNGUS PANEL - CF; ASPERGILLUS CF; BLASTOMYCES CF; COCCIDIODES; HISTOPLASMA CF; MYCELIAL PHASE-HISTO;                        YEAST PHASE-HISTO"
	 OrderType.create description: "G 6 PD SCREEN"
	 OrderType.create description: "G 6 PD QUANT"
	 OrderType.create description: "GABAPENTIN (NEURONTIN)"
	 OrderType.create description: "GAMMA GLOBULIN IGG, CSF"
	 OrderType.create description: "GAMMA GLUTAMYL TRANSFERASE (GGT)"
	 OrderType.create description: "GASTRIC CULTURE AND GRAM STAIN"
	 OrderType.create description: "GASTRIC BRUSH - CYTOLOGY"
	 OrderType.create description: "GASTRIC WASHINGS - CYTOLOGY"
	 OrderType.create description: "GASTRIN"
	 OrderType.create description: "GBM (GLOMERULAR BASEMENT) AB,IGA/IGG"
	 OrderType.create description: "GC SCREEN"
	 OrderType.create description: "GENERAL HEALTH PANEL; CMP, CBC, TSH"
	 OrderType.create description: "GENITAL CULT + GRAM"
	 OrderType.create description: "TEST"
	 OrderType.create description: "GENITAL CULT + GRAM + ANAEROBE"
	 OrderType.create description: "GENITAL CULTURE"
	 OrderType.create description: "GENITAL STREP B"
	 OrderType.create description: "GENTAMICIN"
	 OrderType.create description: "GENPROBE FOR CHLAMYDIA AND/OR GC"
	 OrderType.create description: "GLIADIN AB, IGG AND IGA"
	 OrderType.create description: "GLOMERULAR BASEMENT AB, IGA/IGG"
	 OrderType.create description: "GLUCAGON"
	 OrderType.create description: "GLUCOLA"
	 OrderType.create description: "GLUCOSE"
	 OrderType.create description: "GLUCOSE -  CSF"
	 OrderType.create description: "GLUCOSE -  FLUID"
	 OrderType.create description: "GLUCOSE -  QUANTITATIVE (24 HR)"
	 OrderType.create description: "GLUCOSE -  RANDOM"
	 OrderType.create description: "GLUCOSE - SEMIQUANT (CLINITEST)"
	 OrderType.create description: "GLUCOSE -  ONE HOUR PP"
	 OrderType.create description: "GLUCOSE -  TWO HOUR PP"
	 OrderType.create description: "GLUCOSE TOLERANCE TEST -  1 HOUR; GLUCOSE- FASTING AND 1 HOUR"
	 OrderType.create description: "GLUCOSE TOLERANCE TEST -  2 HOURS; GLUCOSE-FASTING, 1 AND 2 HOUR"
	 OrderType.create description: "GLUCOSE TOLERANCE TEST -  3 HOURS; GLUCOSE-FASTING, 1,2 AND 3 HOURS"
	 OrderType.create description: "GLYCOSYLATED HEMOGLOBIN (A1C)"
	 OrderType.create description: "GM1 AB PANEL"
	 OrderType.create description: "GOLD"
	 OrderType.create description: "GONOCOCCAL ANTIBODIES"
	 OrderType.create description: "GONORRHEA BY DNA PROBE (GENPROBE)"
	 OrderType.create description: "GONORRHEA PROBE BY LCR"
	 OrderType.create description: "GRAM STAIN"
	 OrderType.create description: "GRAM STAIN BUFFY COAT"
	 OrderType.create description: "GROSS CONSULTATION"
	 OrderType.create description: "GROWTH HORMONE"
	 OrderType.create description: "H. PYLORI AB IGG"
	 OrderType.create description: "HAA (HEPATITIS A AB; IGM)"
	 OrderType.create description: "HALDOL"
	 OrderType.create description: "TEST"
	 OrderType.create description: "HALOPERIDOL (HALDOL)"
	 OrderType.create description: "HAM TEST (ACID HEMOLYSIN)"
	 OrderType.create description: "HAPTOGLOBIN"
	 OrderType.create description: "HCG, QUALITATIVE"
	 OrderType.create description: "HCG, QUANTITATIVE"
	 OrderType.create description: "HDL CHOLESTEROL"
	 OrderType.create description: "HEAVY METALS SCREEN, BLOOD; ARSENIC, LEAD, MERCURY"
	 OrderType.create description: "HEAVY METALS SCREEN, URINE"
	 OrderType.create description: "ARSENIC, LEAD, MERCURY"
	 OrderType.create description: "HELICOBACTER CULTURE"
	 OrderType.create description: "HELICOBACTER PYLORII AB"
	 OrderType.create description: "HEMOGLOBIN PLASMA"
	 OrderType.create description: "HEMOGLOBIN, SERUM"
	 OrderType.create description: "HEMOGLOBIN A1C; (GLYCOSALATED HGB)"
	 OrderType.create description: "HEMOGLOBIN ELECTROPHORESIS"
	 OrderType.create description: "HEMOGLOBIN S"
	 OrderType.create description: "HEMOGRAM;  HCT, HGB, MCH, MCV, MCHC, RDW, RBC, WBC, PLATELETS"
	 OrderType.create description: "HEMOPHILUS INFLUENZA TYPE B - BAS; (H INF TYPE B - BAS)"
	 OrderType.create description: "HEMOSIDERIN"
	 OrderType.create description: "HEPARIN ANTI-Xa LMWH"
	 OrderType.create description: "HEPARIN ANTI-Xa UNFRACT"
	 OrderType.create description: "HEPARIN INDUCED THROMBOCYTOPENIA (HIT)"
	 OrderType.create description: "HEPATIC FUNTION PANEL (LIVER PANEL); ALBUMIN, ALKALINE PHOSPHATASE, BILIRUBIN (TOTALANDDIRECT), SGPT, SGOT, TOTAL PROTEIN"
	 OrderType.create description: "HEPATITIS A AB (TOTAL)"
	 OrderType.create description: "HEPATITIS A ANTIBODY- IGM"
	 OrderType.create description: "HEPATITIS B CORE ANTIBODY- IGG"
	 OrderType.create description: "HEPATITIS B CORE ANTIBODY-IGM"
	 OrderType.create description: "HEPATITIS B SURFACE ANTIBODY"
	 OrderType.create description: "HEPATITIS B SURFACE ANTIGEN"
	 OrderType.create description: "HEPATITIS BE ANTIBODY"
	 OrderType.create description: "HEPATITIS BE ANTIGEN"
	 OrderType.create description: "HEPATITIS C ANTIBODY"
	 OrderType.create description: "HEPATITIS C RNA, QUANT"
	 OrderType.create description: "HEPATITIS DELTA AB"
	 OrderType.create description: "HERPES IGG AB SIMPLEX (I  AND II)"
	 OrderType.create description: "HERPES SIMPLEX IGM AB"
	 OrderType.create description: "HERPES CULTURE"
	 OrderType.create description: "HERPES DFA"
	 OrderType.create description: "TEST"
	 OrderType.create description: "HERPES IGM ANTIBODIES"
	 OrderType.create description: "HERPES SIMPLEX VIRUS BY PCR, SERUM"
	 OrderType.create description: "HERPES SIMPLEX VIRUS BY PCR, CSF"
	 OrderType.create description: "HERPES VS VARICELLA CULTURE"
	 OrderType.create description: "HEXOSAMINIDASE A; REFER TO TAY SACHS"
	 OrderType.create description: "HIGH DENSITY LIPOPROTEIN CHOL"
	 OrderType.create description: "HIPPURIC ACID"
	 OrderType.create description: "HISTOPLASMA AB; MYCELIAL AND YEAST PHASE"
	 OrderType.create description: "HIV - REFER TO HUMAN IMMUNODEFICIENCY VIRUS"
	 OrderType.create description: "HIV RAPID SCREEN"
	 OrderType.create description: "HIV-1 AB WESTERN BLOT"
	 OrderType.create description: "HIV-1 DNA BRANCH CHAIN"
	 OrderType.create description: "HIV-1 DNA QUAL BY PCR"
	 OrderType.create description: "HIV-1 P24 ANTIGEN"
	 OrderType.create description: "HIV-1 RNA"
	 OrderType.create description: "HIV-1 RNA QUANT BY PCR"
	 OrderType.create description: "HIV-1 ULTRA SENSITIVE RNA BY PCR"
	 OrderType.create description: "HLA A,B,C PHENOTYPE"
	 OrderType.create description: "HLA AB DETECTION"
	 OrderType.create description: "HLA -  B27"
	 OrderType.create description: "HLA - TYPING A-B-C"
	 OrderType.create description: "HLA TYPING, DR / DQ PHENOTYPE"
	 OrderType.create description: "HOMOCYSTINE"
	 OrderType.create description: "HOMOCYSTINE, URINE"
	 OrderType.create description: "HOMOVANILLIC ACID"
	 OrderType.create description: "HU (NEURONAL NUCLEAR AB)"
	 OrderType.create description: "HUMAN GROWTH HORMONE"
	 OrderType.create description: "HUMAN PLACENTAL LACTOGEN"
	 OrderType.create description: "HYDROXYPROLINE TOTAL"
	 OrderType.create description: "HYDROXYPROLINE; FREE ANDTOTAL HYDROXYPROLINE"
	 OrderType.create description: "IGA, SERUM (IMMUNOGLOBULIN A)"
	 OrderType.create description: "IGD, SERUM (IMMUNOGLOBULIN D)"
	 OrderType.create description: "IGE-SERUM (IMMUNOGLOBULIN E)"
	 OrderType.create description: "IGE TOTAL (IMMUNOGLOBULIN E)"
	 OrderType.create description: "IGF - BINDING PROTEIN 3"
	 OrderType.create description: "IGG-SERUM (IMMUNOGLOBULIN G, SERUM)"
	 OrderType.create description: "IGG - CSF (IMMUNOGLOBULIN G, CSF)"
	 OrderType.create description: "IGG SUBCLASSES"
	 OrderType.create description: "IGG SYNTHESIS RATE; ALBUMIN INDEX, ALBUMIN SERUM, CSF IGG INDEX, IGG CSF"
	 OrderType.create description: "IGM-SERUM (IMMUNOGLOBULIN M, SERUM)"
	 OrderType.create description: "TEST"
	 OrderType.create description: "IMIPRAMINE, TOTAL"
	 OrderType.create description: "IMMUNE COMPLEX"
	 OrderType.create description: "IMMUNOELECTROPHORESIS"
	 OrderType.create description: "IMMUNOELECTROPHORESIS, RANDOM URINE"
	 OrderType.create description: "IMMUNOELECTROPHORESIS, 24 HOUR URINE"
	 OrderType.create description: "IMMUNOGLOBULINS IGG, IGA, IGM"
	 OrderType.create description: "IMMUNOGLOBULIN A"
	 OrderType.create description: "IMMUNOGLOBULIN G"
	 OrderType.create description: "IMMUNOGLOBULIN M"
	 OrderType.create description: "IMMUNOGLOBULIN, IgE TOTAL"
	 OrderType.create description: "INDERAL (PROPRANOLOL)"
	 OrderType.create description: "INDIA INK"
	 OrderType.create description: "INFECTIOUS MONONUCLEOSIS"
	 OrderType.create description: "INFLUENZA A ANTIBODIES, CF"
	 OrderType.create description: "INFLUENZA B ANTIBODIES, CF"
	 OrderType.create description: "INHIBITOR STUDIES - PT"
	 OrderType.create description: "INHIBITOR STUDIES - PTT"
	 OrderType.create description: "INSULIN"
	 OrderType.create description: "INSULIN AB HUMAN"
	 OrderType.create description: "INSULIN LIKE GROWTH FACTOR AB (SOMATAMEDIN C)"
	 OrderType.create description: "INTRINSIC FACTOR ANTIBODIES"
	 OrderType.create description: "IONIZED CALCIUM"
	 OrderType.create description: "IRON"
	 OrderType.create description: "IRON STUDY - IRON; %SATURATION; TIBC; TRANSFERRIN"
	 OrderType.create description: "IRON TISSUE"
	 OrderType.create description: "ISLET CELL AB"
	 OrderType.create description: "ISOPROPANOL"
	 OrderType.create description: "KB STAIN (KEIHAUER BETKE)"
	 OrderType.create description: "KETONES, QUALITATIVE"
	 OrderType.create description: "KIDNEY BIOPSY"
	 OrderType.create description: "KLEIHAUER BETKE (FETAL RBC)"
	 OrderType.create description: "KLONOPIN"
	 OrderType.create description: "KOH WET MOUNT - FUNGUS"
	 OrderType.create description: "L/S RATIO"
	 OrderType.create description: "LACTATE (LACTIC ACID)"
	 OrderType.create description: "LACTATE, CSF"
	 OrderType.create description: "TEST"
	 OrderType.create description: "LACTOSE TOLERANCE; GLUCOSE-FASTING, 1, 2 AND 3"
	 OrderType.create description: "HRS"
	 OrderType.create description: "LAMELLAR BODY COUNT"
	 OrderType.create description: "LAMICTAL"
	 OrderType.create description: "LAMOTRIGINE (LAMICTAL)"
	 OrderType.create description: "LASA-P; (LIPID ASSOCIATED SIALIC ACID)"
	 OrderType.create description: "LATEX-SPECIFIC IGE"
	 OrderType.create description: "LAVAGE PROFILE"
	 OrderType.create description: "LDH"
	 OrderType.create description: "LDH ISOENZYMES"
	 OrderType.create description: "LDH, BODY FLUID"
	 OrderType.create description: "LDH, CSF"
	 OrderType.create description: "LDH ISOENZYMES, FRACTIONATED"
	 OrderType.create description: "LE PREPARATION; (LUPUS ERYTHEMATOSUS ANTIBODIES, SERUM)"
	 OrderType.create description: "LEAD, BLOOD"
	 OrderType.create description: "LEAD, URINE"
	 OrderType.create description: "LEGIONELLA ANTIBODIES"
	 OrderType.create description: "LEGIONELLA ANTIGEN"
	 OrderType.create description: "LEGIONELLA CULTURE"
	 OrderType.create description: "LEPTOSPIRA ANTIBODIES"
	 OrderType.create description: "LEUCINE AMINO PEPTIDASE"
	 OrderType.create description: "LEUKEMIA PROFILE"
	 OrderType.create description: "LH, SERUM; (LUTEINIZING HORMONE, SERUM)"
	 OrderType.create description: "LIPASE, SERUM"
	 OrderType.create description: "LIPID ASSO SIALIC ACID"
	 OrderType.create description: "LIPID PANEL; CHOLESTEROL, HDL, LDL (CALCULATED), TRIGLYCERIDES"
	 OrderType.create description: "LIPID PANEL EXTENDED; CHOLESTEROL, HDL, LDL (CALCULATED), TRIGLYCERIDES, CHOL/HDL, VLDL (CALCULATED)"
	 OrderType.create description: "LIPOPROTEIN A"
	 OrderType.create description: "LITHIUM, SERUM"
	 OrderType.create description: "LIVER KIDNEY MICROSOME AB"
	 OrderType.create description: "LONG CHAIN FATTY ACIDS"
	 OrderType.create description: "LORAZEPAM"
	 OrderType.create description: "LOXAPINE"
	 OrderType.create description: "LUNG MATURITY; (SEE L/S AND LAMELLAR BODY CT)"
	 OrderType.create description: "LUPUS ANTICOAGULANT"
	 OrderType.create description: "LYME-BORRELIA AB"
	 OrderType.create description: "LYMPHOGRANULOMA VENEREUM, CF"
	 OrderType.create description: "TEST"
	 OrderType.create description: "LYMPHOMA PROFILE"
	 OrderType.create description: "LYSOSOMAL ENZYME"
	 OrderType.create description: "MAGNESIUM"
	 OrderType.create description: "MAGNESIUM, RANDOM URINE"
	 OrderType.create description: "MAGNESIUM, 24 HOUR URINE"
	 OrderType.create description: "MALARIAL SMEAR"
	 OrderType.create description: "MARIJUANA, QUAL, URINE, THC"
	 OrderType.create description: "MEASLES (RUBELLA) AB IGG"
	 OrderType.create description: "MEALSES (RUBEOLA) AB IGG"
	 OrderType.create description: "MEASLES (RUBEOLA) AB IGM"
	 OrderType.create description: "MEBARAL (MEPHOBARBITAL)"
	 OrderType.create description: "MECONIUM DRUG PANEL; AMPHETAMINES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE, OPIATES, PHENCYCLIDINE"
	 OrderType.create description: "MERCURY"
	 OrderType.create description: "MERCURY - URINE"
	 OrderType.create description: "METABOLIC SCREEN; CYCTINE, DNPH, FERRIC CHLORIDE, MPS, URINE AMINO ACIDS"
	 OrderType.create description: "METANEPHRINES, TOTAL"
	 OrderType.create description: "METHADONE"
	 OrderType.create description: "METHADONE, QUAL URINE"
	 OrderType.create description: "METHANOL"
	 OrderType.create description: "METHOTREXATE"
	 OrderType.create description: "METHSUXIMIDE / NORMETHSUXIMIDE"
	 OrderType.create description: "METHYLMELONIC ACID"
	 OrderType.create description: "METHYLMELONIC ACID - URINE"
	 OrderType.create description: "MEXILITINE"
	 OrderType.create description: "MHPG , URINE"
	 OrderType.create description: "MICROALBUMIN, 24 HOUR UR QUANT AND CREATININE"
	 OrderType.create description: "MICROALBUMIN, RANDOM UR AND CREATININE"
	 OrderType.create description: "MICROSOMAL AB"
	 OrderType.create description: "MINIMAL BACTERICIDAL CONCENTRATION"
	 OrderType.create description: "MISCELLANEOUS FLUID - CYTOLOGY"
	 OrderType.create description: "MITOCHONDRIAL AB, IGG"
	 OrderType.create description: "MITOCHRONDRIAL ENZYME BIOPSY"
	 OrderType.create description: "MMA (METHOMELONIC ACID QUANT)"
	 OrderType.create description: "TEST"
	 OrderType.create description: "MOLECULAR GENETCS TESTING (SEE LIST BELOW) APO E"
	 OrderType.create description: "DNA FRAG X FACTOR V L MTHFR"
	 OrderType.create description: "PT GENE"
	 OrderType.create description: "PWS/AS"
	 OrderType.create description: "MONONUCLEOSIS TEST"
	 OrderType.create description: "MOTOR SENSORY NEUROPATHY"
	 OrderType.create description: "MPS SPOT TEST"
	 OrderType.create description: "MUCOPOLYSACCHARIDES QUAL - URINE"
	 OrderType.create description: "MULTIPLE SCLEROSIS PROFILE, CSF;  IGG, ALBUMIN-CSF, ALBUMIN INDEX, ALBUMIN-SERUM, CSF BAND, CSF IGG INDEX, IGG/ALBUMIN RATIO, CSF IGG SYNTHESIS RATE, MYELIN BASIC PROTEIN, SERUM BAND"
	 OrderType.create description: "MUMPS AB, IGG"
	 OrderType.create description: "MYCOPLASMA ANTIBODY; IGG AND/OR IGM"
	 OrderType.create description: "MYELIN BASIC PROTEIN"
	 OrderType.create description: "MYOCARDIAL AB"
	 OrderType.create description: "MYOGLOBIN QUANT, SERUM"
	 OrderType.create description: "MYOGLOBIN, URINE"
	 OrderType.create description: "MYSOLINE (PRIMIDONE)"
	 OrderType.create description: "NERVE BIOPSY"
	 OrderType.create description: "NETILMICIN LEVEL, SERUM"
	 OrderType.create description: "NEURONAL IGG AB"
	 OrderType.create description: "NEURONAL NUCLEAR AB"
	 OrderType.create description: "NEURONAL NUCLEAR AB, CSF"
	 OrderType.create description: "NEURON -SPECIFIC ENOLASE"
	 OrderType.create description: "NEURONTIN"
	 OrderType.create description: "NEUTROPHIL AB"
	 OrderType.create description: "NEUTROPHIL OXIDATIVE BURST ASSAY"
	 OrderType.create description: "NEWBORN SCREEN - INITIAL; CAH, GALACTOSEMIA, HEMOGLOBINAPATHY, HOMOSYSTINURIA, HYPOTHYROIDISM, MAPLE SYRUP URINE DISEASE, PHENYLKETONURIA"
	 OrderType.create description: "NEWBORN SCREEN - SECOND; CAH, GALACTOSEMIA, HEMOGLOBINAPATHY, HOMOSYSTINURIA, HYPOTHYROIDISM, MAPLE SYRUP URINE DISEASE, PHENYLKETONURIA"
	 OrderType.create description: "NITROBLUE TETRAZOLIUM DYE TEST"
	 OrderType.create description: "NORPACE, QUANT SERUM (DISOPYRAMIDE)"
	 OrderType.create description: "NORTRIPTYLINE"
	 OrderType.create description: "OBSTETRIC PANEL; CBC, HEPATITIS B SURFACE AG, RUBELLA IGG, RPR, TYPE AND SCREEN"
	 OrderType.create description: "OCCULT BLOOD, FECES"
	 OrderType.create description: "TEST"
	 OrderType.create description: "OCCULT BLOOD, GASTRIC"
	 OrderType.create description: "OLIGOCLONAL BANDING"
	 OrderType.create description: "ORGANIC ACIDS, QUAL"
	 OrderType.create description: "ORGANIC ACIDS, QUANT"
	 OrderType.create description: "OSMOLALITY, SERUM"
	 OrderType.create description: "OSMOLALITY, URINE"
	 OrderType.create description: "OSMOTIC FRAGILITY; INCUBATED/UNINCUBATED"
	 OrderType.create description: "OSTEOCALCIN"
	 OrderType.create description: "OVA AND PARASITES"
	 OrderType.create description: "OVARY AB IGG"
	 OrderType.create description: "OXALATES, URINE"
	 OrderType.create description: "PAP SMEAR"
	 OrderType.create description: "PARA INFLUENZA AB - CF; PARAINFLUENZA TYPES 1,2 AND 3"
	 OrderType.create description: "PARACENTESIS - CYTOLOGY"
	 OrderType.create description: "PARATHYROID HORMONE INTACT (IPTH)"
	 OrderType.create description: "PARATHYROID HORMONE INTACT (IPTH);"
	 OrderType.create description: "INTRAOPERATIVE"
	 OrderType.create description: "PARIETAL CELL AB, IGG"
	 OrderType.create description: "PARVOVIRUS B19 AB. IGG/IGM"
	 OrderType.create description: "PEDIATRIC ALLERGY TEST 1; EGG WHITE, MILK, WHEAT, OAT, SOYBEAN"
	 OrderType.create description: "PEDIATRIC ALLERGY TEST 2; D.FARINAE, D.PTERNYSSINUS, DOG EPITHELIUM, CAT EPITHELIUM, ALTERNARIA ENIUS, EGG WHITE, MILK, WHEAT, CORN, SOYBEAN, HOUSE DUST GREER"
	 OrderType.create description: "PEMPHIGOID AB (EPIDERMAL)"
	 OrderType.create description: "PENTOBARBITOL"
	 OrderType.create description: "PERICARDIAL FLUID - CYTOLOGY"
	 OrderType.create description: "PERINUCLEAR FACTOR AB"
	 OrderType.create description: "PERIDONEAL WASHING - CYTOLOGY"
	 OrderType.create description: "PERTUSSIS CULTURE"
	 OrderType.create description: "PERTUSSIS FA STAIN; SEE MICROBIOLOGY SECTION"
	 OrderType.create description: "PH, FECAL"
	 OrderType.create description: "PH, URINE"
	 OrderType.create description: "PH - OTHER"
	 OrderType.create description: "PHENOBARBITAL"
	 OrderType.create description: "PHENYLALANINE, QUANT"
	 OrderType.create description: "PHENYTOIN (DILANTIN)"
	 OrderType.create description: "TEST"
	 OrderType.create description: "PHENYTOIN FREE; QUANT"
	 OrderType.create description: "PHOSPHATASE, ALKALINE; ISOENZYME"
	 OrderType.create description: "PHOSPHORUS, SERUM"
	 OrderType.create description: "PHOSPHORUS, 24 HOUR URINE"
	 OrderType.create description: "PHOSPHORUS, RANDOM URINE"
	 OrderType.create description: "PHYTANIC ACID"
	 OrderType.create description: "PINWORM TAPE PREP"
	 OrderType.create description: "PKU (PHENYLALANINE, QUANT)"
	 OrderType.create description: "PLASMA HEMOGLOBIN"
	 OrderType.create description: "PLASMINOGEN"
	 OrderType.create description: "PLATELET AB - DIRECT"
	 OrderType.create description: "PLATELET AB - INDIRECT"
	 OrderType.create description: "PLATELET AGGREGGATE"
	 OrderType.create description: "PLATELET COUNT - HEMOGRAM"
	 OrderType.create description: "PLATELET FACTOR (PF-4) AB"
	 OrderType.create description: "PLAVIX"
	 OrderType.create description: "PLEURAL FLUID - CYTOLOGY"
	 OrderType.create description: "PNEUMOCYSTIS DFA"
	 OrderType.create description: "POLIO SEROTYPE; POLIO TYPES 1, 2, AND 3"
	 OrderType.create description: "PORPHOBILINOGEN DEAMINASE (URO1"
	 OrderType.create description: "SYNTHETASE)"
	 OrderType.create description: "PORPHOBILINOGEN, QUALITATIVE"
	 OrderType.create description: "PORPHOBILINOGEN, QUANTITATIVE"
	 OrderType.create description: "PORPHYRINS, URINE QUANTITATIVE; COPROPORPHYRIN, UROPORPHYRIN"
	 OrderType.create description: "POTASSIUM"
	 OrderType.create description: "POTASSIUM, FLUID"
	 OrderType.create description: "POTASSIUM, RANDOM URINE"
	 OrderType.create description: "POTASSIUM, 24 HOUR URINE"
	 OrderType.create description: "PRE-ALBUMIN LEVEL"
	 OrderType.create description: "PREGNANCY, QUALITATIVE"
	 OrderType.create description: "PREGNANCY, QUALITATIVE"
	 OrderType.create description: "PREGNANETRIOL, URINE"
	 OrderType.create description: "PRIMIDONE"
	 OrderType.create description: "PROCAINAMIDE; NAPA"
	 OrderType.create description: "TEST"
	 OrderType.create description: "PROCALCITONIN ASSAY (PCT)"
	 OrderType.create description: "PROGESTERONE"
	 OrderType.create description: "PROGRAF (TACROLIMUS)"
	 OrderType.create description: "PROINSULIN"
	 OrderType.create description: "PROLACTIN"
	 OrderType.create description: "PROPOXYPHENE"
	 OrderType.create description: "PROPRANOLOL"
	 OrderType.create description: "PROSTATE SPECIFIC ANTIGEN  (PSA)"
	 OrderType.create description: "PROSTATIC ACID PHOSPHATASE"
	 OrderType.create description: "PROTEIN ELECTROPHORESIS; 24 HOUR URINE"
	 OrderType.create description: "PROTEIN ELECTROPHORESIS- CSF; ALBUMIN, ALPHA-2, BETA, GAMMA, PRE-ALBUMIN, TOTAL PROTEIN"
	 OrderType.create description: "PROTEIN ELECTROPHORESIS- SERUM; ALBUMIN, ALPHA-1, ALPHA-2, BETA, GAMMA, TOTAL PROTEIN"
	 OrderType.create description: "PROTEIN - C  FUNCTIONAL"
	 OrderType.create description: "PROTEIN - S, FUNCTIONAL"
	 OrderType.create description: "PROTEIN; TOTAL"
	 OrderType.create description: "PROTEIN, TOTAL BODY FLUID"
	 OrderType.create description: "PROTEIN, TOTAL CSF"
	 OrderType.create description: "PROTEIN, TOTAL 24HR URINE"
	 OrderType.create description: "PROTEIN, TOTAL 12HR URINE"
	 OrderType.create description: "PROTEIN, TOTAL RANDOM URINE"
	 OrderType.create description: "PROTHROMBIN GENE/PCR"
	 OrderType.create description: "PROTHROMBIN TIME (PT)"
	 OrderType.create description: "PROTRIPTYLINE"
	 OrderType.create description: "PROZAC (FLUOXETINE)"
	 OrderType.create description: "PSA (PROSTATE SPECIFIC ANTIGEN)"
	 OrderType.create description: "PSEUDOCHOLINESTERASE"
	 OrderType.create description: "PT (PROTHROMBIN TIME)"
	 OrderType.create description: "PT MIXING STUDY SCREEN-QUAL"
	 OrderType.create description: "PTH, INTACT TERMINAL"
	 OrderType.create description: "PTT"
	 OrderType.create description: "PTT MIXING STUDY SCREEN (INHIBITOR STUDY)"
	 OrderType.create description: "PURKINJI CELL"
	 OrderType.create description: "PYRUVATE (PYRUVIC ACID)"
	 OrderType.create description: "TEST"
	 OrderType.create description: "PYRUVATE, CSF"
	 OrderType.create description: "Q FEVER ANTIBODIES"
	 OrderType.create description: "QUANTIFERON TB GOLD"
	 OrderType.create description: "QUINIDINE"
	 OrderType.create description: "RAPID HIV"
	 OrderType.create description: "RAJI CELL ASSAY"
	 OrderType.create description: "RAPID STREP THROAT"
	 OrderType.create description: "RAST-LATEX ALLERGY IGE"
	 OrderType.create description: "RBC CHOLINESTERASE"
	 OrderType.create description: "RBC FOLATE"
	 OrderType.create description: "REDUCING SUBSTANCE"
	 OrderType.create description: "RENAL BIOPSY"
	 OrderType.create description: "RENAL FUNCTION PANEL; ALBUMIN, CALCIUM, CO2, CHLORIDE, CREATININE, GLUCOSE, PHOSPHORUS, POTASSIUM, SODIUM, BUN"
	 OrderType.create description: "RENIN"
	 OrderType.create description: "RESPIRATORY CULTURE"
	 OrderType.create description: "RESPIRATORY CULTURE + GRAM"
	 OrderType.create description: "RESP SYNCYTIAL VIRUS AB"
	 OrderType.create description: "RETICULOCYTE COUNT"
	 OrderType.create description: "REVERSE T3"
	 OrderType.create description: "RF (RHEUMATOID FACTOR)"
	 OrderType.create description: "RH NEGATIVE  WORKUP; ABO, RH, FETAL SCREEN- FMH, INDIRECT ANTIGLOBIN"
	 OrderType.create description: "RHEUMATOID FACTOR"
	 OrderType.create description: "RIBOSOMAL P PROTEIN IGG"
	 OrderType.create description: "ROCKY MOUNTAIN SPOTTED FEVER"
	 OrderType.create description: "ROTAVIRUS"
	 OrderType.create description: "RPR (SYPHILIS) SCREEN"
	 OrderType.create description: "RSV AB"
	 OrderType.create description: "RSV - DFA; (RESPIRATORY SYNCYTIAL VIRUS ANTIBODY)"
	 OrderType.create description: "RUBELLA AB IgM"
	 OrderType.create description: "RUBELLA SCREEN, IGG"
	 OrderType.create description: "RUBEOLA (MEASLES) AB IGM"
	 OrderType.create description: "RUBEOLA (MEASLES) AB,IGG"
	 OrderType.create description: "SALICYLATE"
	 OrderType.create description: "SARS"
	 OrderType.create description: "SCABIES PREP"
	 OrderType.create description: "TEST"
	 OrderType.create description: "SCHLICTER TEST; SEE SERUM-CIDAL TEST"
	 OrderType.create description: "SEDIMENTATION RATE (WESTERGREN)"
	 OrderType.create description: "SEROTONIN, SERUM"
	 OrderType.create description: "SEROTONIN, URINE"
	 OrderType.create description: "SEROTONIN, WHOLE BLOOD"
	 OrderType.create description: "SERUM CIDAL PEAK"
	 OrderType.create description: "SERUM CIDAL TROUGH"
	 OrderType.create description: "SERUM FOLATE"
	 OrderType.create description: "SGOT (AST)"
	 OrderType.create description: "SGOT, CSF"
	 OrderType.create description: "SGOT , FLUID"
	 OrderType.create description: "SGPT (ALT)"
	 OrderType.create description: "SIALIC ACID - LIPID ASSOC (LASA)"
	 OrderType.create description: "SICKLE CELL"
	 OrderType.create description: "SINEQUAN (DOXEPIN)"
	 OrderType.create description: "SJOGRENS AB"
	 OrderType.create description: "SKELETAL MUSCLE ANTIBODY"
	 OrderType.create description: "SKIN LESION SCRAPE - CYTOLOGY"
	 OrderType.create description: "SMEAR - EOS"
	 OrderType.create description: "SMEAR - PATHOLOGY"
	 OrderType.create description: "SMEAR - POLYS"
	 OrderType.create description: "SMITH SMOOTH MUSCLE AB"
	 OrderType.create description: "SMOOTH MUSCLE AB"
	 OrderType.create description: "SODIUM"
	 OrderType.create description: "SODIUM, FLUID"
	 OrderType.create description: "SODIUM, RANDOM URINE"
	 OrderType.create description: "SODIUM, 24 HOUR URINE"
	 OrderType.create description: "SOMATAMEDIN C; (INSULIN LIKE GROWTH FACTOR I)"
	 OrderType.create description: "SPERM AB IGG"
	 OrderType.create description: "SPERM - POST VASECTOMY"
	 OrderType.create description: "SPUTUM - CYTOLOGY"
	 OrderType.create description: "SSA AND SSB; (SJOGREN'S PANEL)"
	 OrderType.create description: "ST. LOUIS ENCEPHALITIS AB"
	 OrderType.create description: "STEM CELL ASSAY"
	 OrderType.create description: "STONE ANALYSIS"
	 OrderType.create description: "STOOL CULTURE; (INCL SALOMELLA, SHIGELLA, CAMPYLOBACTER)"
	 OrderType.create description: "TEST"
	 OrderType.create description: "STREP SCREEN"
	 OrderType.create description: "STREPTOLYSIN O AB"
	 OrderType.create description: "STREPTOZYME"
	 OrderType.create description: "STRIATED MUSCLE AB, IGG"
	 OrderType.create description: "STRONGYLOIDES IGG"
	 OrderType.create description: "SUDAN BLACK"
	 OrderType.create description: "SUGAR WATER TEST"
	 OrderType.create description: "SULFADIAZINE (SULFONANIDES)"
	 OrderType.create description: "SWEAT CHLORIDE"
	 OrderType.create description: "SYNOVIAL FLUID; CRYSTALS"
	 OrderType.create description: "SYNOVIAL FLUID; MUCIN CLOT, VISCOSITY"
	 OrderType.create description: "SYPHILIS ANTIBODY"
	 OrderType.create description: "SYPHILIS SCREEN - CSF (VDRL)"
	 OrderType.create description: "SYPHILIS SCREEN - RPR"
	 OrderType.create description: "T3; (TRIIODOTHYRONINE, TOTAL)"
	 OrderType.create description: "T3, FREE (TRIIODOTHYRONINE)"
	 OrderType.create description: "T3, REVERSE"
	 OrderType.create description: "T3, UPTAKE (RESIN UPTAKE)"
	 OrderType.create description: "T4; (THYROXINE)"
	 OrderType.create description: "T4, FREE (THYROXINE; FREE)"
	 OrderType.create description: "T CELL LYMPHOCYTE PHENOTYPING (CD4/CD8)"
	 OrderType.create description: "TACROLIMUS (FK506)"
	 OrderType.create description: "TAY-SACHS"
	 OrderType.create description: "TEGRETOL; (CARBAMAZEPINE)"
	 OrderType.create description: "TEICHOIC ACID ANTIBODIES"
	 OrderType.create description: "TEMAZEPAM"
	 OrderType.create description: "TESTOSTERONE FREE"
	 OrderType.create description: "TESTOSTERONE TOTAL"
	 OrderType.create description: "TETANUS TITER - IGG"
	 OrderType.create description: "THEOPHYLLINE"
	 OrderType.create description: "THIAMINE (VITAMIN B1)"
	 OrderType.create description: "THIOCYANATE"
	 OrderType.create description: "THIORIDAZINE/MESORIDAZIN"
	 OrderType.create description: "THIOTHIXENE"
	 OrderType.create description: "THROAT CULTURE"
	 OrderType.create description: "THROMBIN TIME (TCT)"
	 OrderType.create description: "THYROGLOBIN; iNCL THYROGLOCULIN AB AND % THYROGLOBUIN RECOVERED"
	 OrderType.create description: "TEST"
	 OrderType.create description: "THYROGLOBULIN AB"
	 OrderType.create description: "THYROID AB; INCL TPO AB AND THYROGLOBULIN AB"
	 OrderType.create description: "THYROID GROWTH STIM HORMONE RECEPTOR AB"
	 OrderType.create description: "THYROID STIMULATING IMMUNOGLOBULIN (TSI)"
	 OrderType.create description: "THYROID STIMULATING HORMONE (TSH)"
	 OrderType.create description: "THYROXINE (T4)"
	 OrderType.create description: "THYROXINE BINDING GLOBULIN (TBG)"
	 OrderType.create description: "THYROXINE FREE (FREE T4)"
	 OrderType.create description: "TISSUE CULT + GRAM + ANAEROBE"
	 OrderType.create description: "TISSUE SPECIMEN GROSS ONLY"
	 OrderType.create description: "TOBRAMYCIN"
	 OrderType.create description: "TOCAINIDE"
	 OrderType.create description: "TOLUENE"
	 OrderType.create description: "TOPIRAMATE"
	 OrderType.create description: "TOTAL BILIRUBIN; INCLUDES CONJUGATED BILIRUBIN"
	 OrderType.create description: "TOTAL PROTEIN"
	 OrderType.create description: "TOTAL PROTEIN -  CSF"
	 OrderType.create description: "TOTAL PROTEIN - FLUID"
	 OrderType.create description: "TOTAL PROTEIN - RANDOM"
	 OrderType.create description: "TOTAL PROTEIN - 12 HOUR URINE"
	 OrderType.create description: "TOTAL PROTEIN - 24 HOUR URINE"
	 OrderType.create description: "TOXOPLASMA - IgG"
	 OrderType.create description: "TOXOPLASMA -  IgM"
	 OrderType.create description: "TRANSFERRIN"
	 OrderType.create description: "TRANSFUSION RXN"
	 OrderType.create description: "TRAXENE; (CLORAZEPATE OR NORDIAZEPAM)"
	 OrderType.create description: "TRAUMA LAVAGE; BILE, RBC, FOOD PARTICLES, GRAM STAIN, NUCLEATED CELLS"
	 OrderType.create description: "TRAZODONE"
	 OrderType.create description: "TRICHINELLA SPIRILLS"
	 OrderType.create description: "TRICYCLIC ANTIDEPRESSANT-SERUM"
	 OrderType.create description: "TRIGLYCERIDES"
	 OrderType.create description: "TEST"
	 OrderType.create description: "TROPONIN I"
	 OrderType.create description: "TSH (THYROID STIMULATING HORMONE)"
	 OrderType.create description: "TSI (THYROID STIM IMMUNOGLOBULIN)"
	 OrderType.create description: "TYPE - ABO AND RH"
	 OrderType.create description: "TYPE AND CROSSMATCH; ABO, CROSSMATCH, INDIRECT ANTIGLOBIN, RH"
	 OrderType.create description: "TYPE AND SCREEN; ABO, INDIRECT ANTIGLOBULIN, RH"
	 OrderType.create description: "TYPHUS FEVER AB IGG/IGM"
	 OrderType.create description: "TZANCK/HERPES"
	 OrderType.create description: "ULTRACENTRIFUGED SPECIMEN"
	 OrderType.create description: "URIC ACID"
	 OrderType.create description: "URIC ACID - 24 HOUR URINE"
	 OrderType.create description: "URIC ACID - RANDOM URINE"
	 OrderType.create description: "URINALYSIS,  ROUTINE; BILE, CLARITY, COLOR, GLUCOSE, KETONES, LEUKOCYTE ESTERASE, NITRITE, OCC.BLOOD, PH, PROTEIN, SP.GR., UROBILINOGEN-QUAL"
	 OrderType.create description: "URINARY EOSINOPILS"
	 OrderType.create description: "URINE - CYTOLOGY"
	 OrderType.create description: "URINE CULTURE"
	 OrderType.create description: "URINE CYSTINE SCREEN"
	 OrderType.create description: "URINE ORGANIC ACIDS"
	 OrderType.create description: "URINE UREA NITROGEN, RANDOM"
	 OrderType.create description: "URINE UREA NITROGEN, 24 HOUR"
	 OrderType.create description: "URO - 1   - SYNTHETASE (PORPHOBILINOGEN DEAMINASE)"
	 OrderType.create description: "UROBILINOGEN QUANT"
	 OrderType.create description: "VALPROIC ACID"
	 OrderType.create description: "VANCOMYCIN"
	 OrderType.create description: "VARICELLA AB, IGG AND/OR IGM"
	 OrderType.create description: "VARICELLA ZOSTER AB, IGG"
	 OrderType.create description: "VARICELLA ZOSTER AB, IGG/IGM"
	 OrderType.create description: "VARICELLA ZOSTER AB, IGM"
	 OrderType.create description: "VARICELLA ZOSTER BY PCR, CSF"
	 OrderType.create description: "VASOACTIVE INTESTINAL PEPTIDE"
	 OrderType.create description: "VASOPRESSIN, (ADH)"
	 OrderType.create description: "VDRL - CSF (SYPHILIS SCREEN)"
	 OrderType.create description: "VERAPAMIL"
	 OrderType.create description: "VIBRIO CULTURE"
	 OrderType.create description: "TEST"
	 OrderType.create description: "VIRAL CULTURE"
	 OrderType.create description: "VIRAL CULTURE -  BLOOD"
	 OrderType.create description: "VIRAL  RESPIRATORY CULTURE  - DFA;"
	 OrderType.create description: "ADENOVIRUS, INFLUENZA A AND B, PARAINFLUENZA 1,"
	 OrderType.create description: "2 AND 3"
	 OrderType.create description: "VISCOSITY"
	 OrderType.create description: "VITAMIN A"
	 OrderType.create description: "VITAMIN B1 (THIAMIN)"
	 OrderType.create description: "VITAMIN B-6 (PYRIDOXAL PHOS)"
	 OrderType.create description: "VITAMIN B-12"
	 OrderType.create description: "VITAMIN C"
	 OrderType.create description: "VITAMIN D TOTAL (D2 AND D3)"
	 OrderType.create description: "VITAMIN D, 1,  25 - DIHYDROXY"
	 OrderType.create description: "VITAMIN E (TOCOPHEROL ALPHA)"
	 OrderType.create description: "VLDL - VERY LOW DENSITY LIPOPROTEIN"
	 OrderType.create description: "VMA - URINE; HOMOVANILLIC ACID"
	 OrderType.create description: "VON WILLEBRAND FACTOR AG RISTOCETIN CO- FACTOR"
	 OrderType.create description: "VRE SCREEN"
	 OrderType.create description: "WESTERN BLOT"
	 OrderType.create description: "WEST NILE VIRUS"
	 OrderType.create description: "WET MOUNT - CLUE CELLS"
	 OrderType.create description: "WET MOUNT - FUNGUS"
	 OrderType.create description: "WET MOUNT - TRICHOMONAS"
	 OrderType.create description: "WET MOUNT -  YEAST"
	 OrderType.create description: "WOUND CULTURE + GRAM"
	 OrderType.create description: "WOUND CULTURE + GRAM + ANAEROBE"
	 OrderType.create description: "XYLOSE ABSORPTION"
	 OrderType.create description: "YELLOW FEVER AB (ST. LOUIS ENCEPHALITIS)"
	 OrderType.create description: "YERSINIA  AB; YERSINIA E, TYPES 3, 8 AND 9, YERSINIA P"
	 OrderType.create description: "YERSINIA CULTURE STOOL"
	 OrderType.create description: "YO (PURKINJE CELL)"
	 OrderType.create description: "ZARONTIN  (ETHOSUXIMIDE)"
	 OrderType.create description: "ZINC"
	 OrderType.create description: "ZINC PROTOPORPHYRIN"
  end

  def down
  end
end
