class PopulateOrderTypesWithCategories < ActiveRecord::Migration

  def up
  	 OrderType.create category: "Lab Test",  description: "5-HIAA, QUANTATIVE"
	 OrderType.create category: "Lab Test",  description: "5-NUCLEOTIDASE"
	 OrderType.create category: "Lab Test",  description: "8 METHOXYPSORALENE"
	 OrderType.create category: "Lab Test",  description: "8-MOP"
	 OrderType.create category: "Lab Test",  description: "11-DEOXYCORTISOL"
	 OrderType.create category: "Lab Test",  description: "17-KETOGENIC STEROIDS"
	 OrderType.create category: "Lab Test",  description: "17-KETOSTEROIDS"
	 OrderType.create category: "Lab Test",  description: "17- OH CORTICOSTEROID"
	 OrderType.create category: "Lab Test",  description: "17-OH PROGESTERONE"
	 OrderType.create category: "Lab Test",  description: "ACETAMINOPHEN"
	 OrderType.create category: "Lab Test",  description: "ACETONE, QUALITATIVE"
	 OrderType.create category: "Lab Test",  description: "ACETYL RECEPTOR BIND AB"
	 OrderType.create category: "Lab Test",  description: "ACETYL RECEPTOR BLOCK AB"
	 OrderType.create category: "Lab Test",  description: "ACETYL RECEPTOR; MODULATING AB"
	 OrderType.create category: "Lab Test",  description: "ACID FAST BACILLUS CULTURE AND STAIN"
	 OrderType.create category: "Lab Test",  description: "ACTH"
	 OrderType.create category: "Lab Test",  description: "ACUTE HEPATITIS PANEL"
	 OrderType.create category: "Lab Test",  description: "ADENOVIRUS CF"
	 OrderType.create category: "Lab Test",  description: "ADRENAL AB"
	 OrderType.create category: "Lab Test",  description: "ADRENOCORTICOTROPIC HORMONE (ACTH)"
	 OrderType.create category: "Lab Test",  description: "AF BILIRUBIN; DELTA OD; UNCONJUGATED BILIRUBIN"
	 OrderType.create category: "Lab Test",  description: "AFB BLOOD CULTURE"
	 OrderType.create category: "Lab Test",  description: "AFP AMNIOTIC FLUID"
	 OrderType.create category: "Lab Test",  description: "AFP MATERNAL"
	 OrderType.create category: "Lab Test",  description: "AFP PLUS"
	 OrderType.create category: "Lab Test",  description: "AFP MS4 (QUAD)"
	 OrderType.create category: "Lab Test",  description: "AFP, TUMOR MARKER"
	 OrderType.create category: "Lab Test",  description: "ALBUMIN"
	 OrderType.create category: "Lab Test",  description: "ALBUMIN, BODY FLUID"
	 OrderType.create category: "Lab Test",  description: "ALCOHOL"
	 OrderType.create category: "Lab Test",  description: "ALDOLASE"
	 OrderType.create category: "Lab Test",  description: "ALDOSTERONE"
	 OrderType.create category: "Lab Test",  description: "ALDOSTERONE, URINE"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "ALKALINE PHOSPHATASE"
	 OrderType.create category: "Lab Test",  description: "ALKALINE PHOSPHATASE ISOENZYME"
	 OrderType.create category: "Lab Test",  description: "ALPHA FETOPROTEIN AMNIOTIC FLUID"
	 OrderType.create category: "Lab Test",  description: "ALPHA FETOPROTEIN MATERNAL"
	 OrderType.create category: "Lab Test",  description: "ALPHA FETO PROTEIN PLUS"
	 OrderType.create category: "Lab Test",  description: "ALPHA FETOPROTEIN; TUMOR MARKER"
	 OrderType.create category: "Lab Test",  description: "ALPHA-1 ANTITRYPSIN"
	 OrderType.create category: "Lab Test",  description: "ALPHA-1 ANTITRYPSIN, FECAL"
	 OrderType.create category: "Lab Test",  description: "ALT (SGPT)"
	 OrderType.create category: "Lab Test",  description: "ALUMINUM"
	 OrderType.create category: "Lab Test",  description: "ALUMINUM, UIRNE"
	 OrderType.create category: "Lab Test",  description: "AMIKACIN"
	 OrderType.create category: "Lab Test",  description: "AMINO ACID QUAL SCREEN"
	 OrderType.create category: "Lab Test",  description: "AMINO ACID QUAL SCREEN, UR"
	 OrderType.create category: "Lab Test",  description: "AMINO ACID QUANT PLASMA"
	 OrderType.create category: "Lab Test",  description: "AMINO ACID QUANT, UR"
	 OrderType.create category: "Lab Test",  description: "AMINO ACIDS, CSF"
	 OrderType.create category: "Lab Test",  description: "AMINOLEVULINIC ACID"
	 OrderType.create category: "Lab Test",  description: "AMIODARONE"
	 OrderType.create category: "Lab Test",  description: "AMITRIPTYLINE/NORTRIPTYLINE"
	 OrderType.create category: "Lab Test",  description: "AMMONIA"
	 OrderType.create category: "Lab Test",  description: "AMOEBIASIS"
	 OrderType.create category: "Lab Test",  description: "AMOXAPINE (ASCENDIN)"
	 OrderType.create category: "Lab Test",  description: "AMYLASE"
	 OrderType.create category: "Lab Test",  description: "AMYLASE, BODY FLUID"
	 OrderType.create category: "Lab Test",  description: "AMYLASE, URINE - TIMED"
	 OrderType.create category: "Lab Test",  description: "AMYLASE ISOENZYMES; PANCREATIC, SALIVARY, TOTAL AMYLASE"
	 OrderType.create category: "Lab Test",  description: "AMYLASE, URINE - RANDOM"
	 OrderType.create category: "Lab Test",  description: "ANA SCREEN"
	 OrderType.create category: "Lab Test",  description: "ANA PROFILE;  SMITH, RNP / SMITH, SCL-70, SSA, SSB, JO-1, dsDNA"
	 OrderType.create category: "Lab Test",  description: "ANA BY IFA"
	 OrderType.create category: "Lab Test",  description: "ANAEROBIC CULTURE"
	 OrderType.create category: "Lab Test",  description: "ANCA PANEL"
	 OrderType.create category: "Lab Test",  description: "ANDROSTANEDIONE"
	 OrderType.create category: "Lab Test",  description: "ANGIOTENSIN CONVERTING ENZYME (ACE)"
	 OrderType.create category: "Lab Test",  description: "ANGIOTENSIN CONVERTING ENZYME,CSF"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "ANTENATAL RH NEG WORK UP; ABO, INDIRECT ANTIGLOBULIN, RH"
	 OrderType.create category: "Lab Test",  description: "ANTIBODY TITER"
	 OrderType.create category: "Lab Test",  description: "ANTICARDIOLIPIN; IGM, IGG, IGA"
	 OrderType.create category: "Lab Test",  description: "ANTINEUTROPHIL CYTO AB; (ANCA PANEL)"
	 OrderType.create category: "Lab Test",  description: "ANTINUCLEAR AB; (ANA ACREEN)"
	 OrderType.create category: "Lab Test",  description: "ANTISTREPTOLYSIN O"
	 OrderType.create category: "Lab Test",  description: "ANTITHROMBIN III"
	 OrderType.create category: "Lab Test",  description: "APC RESISTANCE PROFILE;  APC PTT BASED RESIST, APC PTT RATIO, APC PT BASED RESIS"
	 OrderType.create category: "Lab Test",  description: "APOLIPOPROTEIN A1"
	 OrderType.create category: "Lab Test",  description: "APOLIPOPROTEIN B-100"
	 OrderType.create category: "Lab Test",  description: "APOLIPOPROTEIN E BY PCR"
	 OrderType.create category: "Lab Test",  description: "APT TEST"
	 OrderType.create category: "Lab Test",  description: "ARBOVIRUS PANEL IGM"
	 OrderType.create category: "Lab Test",  description: "ARBOVIRUS PANEL IGG"
	 OrderType.create category: "Lab Test",  description: "ARGININE VASOPRESSIN HORMONE"
	 OrderType.create category: "Lab Test",  description: "ARIZONA ALLERGY, IGE"
	 OrderType.create category: "Lab Test",  description: "ARSENIC, BLOOD"
	 OrderType.create category: "Lab Test",  description: "ARSENIC, URINE"
	 OrderType.create category: "Lab Test",  description: "ARTHRITIS PANEL; URIC ACID, SED RATE, ANA SCREEN, RHEUMATOID FACTOR"
	 OrderType.create category: "Lab Test",  description: "ARYLSULFATASE A, URINE"
	 OrderType.create category: "Lab Test",  description: "ASO (STREPTOLYSIN O AB)"
	 OrderType.create category: "Lab Test",  description: "ASPERGILLUS ANTIBODY CF"
	 OrderType.create category: "Lab Test",  description: "ASPERGILLUS ID"
	 OrderType.create category: "Lab Test",  description: "ASPIRIN RESISTANCE"
	 OrderType.create category: "Lab Test",  description: "AST (SGOT)"
	 OrderType.create category: "Lab Test",  description: "ATRIAL NUTRIURETIC FACTOR"
	 OrderType.create category: "Lab Test",  description: "AUTOPSY"
	 OrderType.create category: "Lab Test",  description: "VITAMIN B-12"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "BARBITURATES"
	 OrderType.create category: "Lab Test",  description: "BASIC METBOLIC PANEL; BUN, CREATININE, ELECTROLYTES, GLUCOSE, CALCIUM"
	 OrderType.create category: "Lab Test",  description: "BCR ANALYSIS"
	 OrderType.create category: "Lab Test",  description: "BCR ANALYSIS"
	 OrderType.create category: "Lab Test",  description: "BENCE-JONES PROTEIN,PROTEIN"
	 OrderType.create category: "Lab Test",  description: "BETA - CAROTENE"
	 OrderType.create category: "Lab Test",  description: "BETA - GLUCURONIDASE"
	 OrderType.create category: "Lab Test",  description: "BETA - HCG, QUALITATIVE AND QUANTITATIVE"
	 OrderType.create category: "Lab Test",  description: "BETA - HYDROXYBUTYRIC ACID"
	 OrderType.create category: "Lab Test",  description: "BETA -2 - MICROGLOBULINS"
	 OrderType.create category: "Lab Test",  description: "B2 TRANSFERRIN"
	 OrderType.create category: "Lab Test",  description: "BETHESDA ASSAY QUANT"
	 OrderType.create category: "Lab Test",  description: "BILE ACIDS, FRACTIONATED; DIHYDROXY, TRIHYDROXY"
	 OrderType.create category: "Lab Test",  description: "BILIRUBIN; NEONATAL; BILIRUBIN-TOTAL, BILIRUBIN-CONJUGATED"
	 OrderType.create category: "Lab Test",  description: "BILIRUBIN, BODY FLUID"
	 OrderType.create category: "Lab Test",  description: "BILIRUBIN; TOTAL AND DIRECT"
	 OrderType.create category: "Lab Test",  description: "BLASTOMYCES ANTIBODY, CF"
	 OrderType.create category: "Lab Test",  description: "BLASTOMYCES ID"
	 OrderType.create category: "Lab Test",  description: "BLEEDING TIME - ROUTINE"
	 OrderType.create category: "Lab Test",  description: "BLEEDING TIME - SURGICUTT"
	 OrderType.create category: "Lab Test",  description: "BLOOD CULTURE"
	 OrderType.create category: "Lab Test",  description: "BLOOD TYPE - ABO AND RH"
	 OrderType.create category: "Lab Test",  description: "BLOOD TYPE AND RH - CORD"
	 OrderType.create category: "Lab Test",  description: "BNP"
	 OrderType.create category: "Lab Test",  description: "BODY FLD CULT + GRAM + ANAEROBE"
	 OrderType.create category: "Lab Test",  description: "BONE GLA PROTEIN"
	 OrderType.create category: "Lab Test",  description: "BONE MARROW ASP"
	 OrderType.create category: "Lab Test",  description: "BONE MARROW - STAIN"
	 OrderType.create category: "Lab Test",  description: "BORRELIA - LYME AB"
	 OrderType.create category: "Lab Test",  description: "BORRELIA HERMSII AB"
	 OrderType.create category: "Lab Test",  description: "BOTULISM"
	 OrderType.create category: "Lab Test",  description: "BREAST FLUID - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "BROMIDE"
	 OrderType.create category: "Lab Test",  description: "BRONCHIAL BRUSH - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "BRONCHIAL WASH - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "BRUCELLA BATTERY;   B.ABORTUS, B.MELETENSIS, B.SUIS"
	 OrderType.create category: "Lab Test",  description: "BUCCAL SMEAR - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "BUN"
	 OrderType.create category: "Lab Test",  description: "C-1 - ESTERASE INHIBITOR"
	 OrderType.create category: "Lab Test",  description: "C1Q BINDING ASSAY"
	 OrderType.create category: "Lab Test",  description: "C - 3 COMPLEMENT"
	 OrderType.create category: "Lab Test",  description: "C3,C4 COMPLEMENT"
	 OrderType.create category: "Lab Test",  description: "C - 4 COMPLEMENT"
	 OrderType.create category: "Lab Test",  description: "C - PEPTIDE, SERUM"
	 OrderType.create category: "Lab Test",  description: "C - REACTIVE PROTEIN, HIGHLY SENSITIVE"
	 OrderType.create category: "Lab Test",  description: "CA 125"
	 OrderType.create category: "Lab Test",  description: "CA 19-9"
	 OrderType.create category: "Lab Test",  description: "CA 27.29"
	 OrderType.create category: "Lab Test",  description: "CA15-3 (CA 27-29)"
	 OrderType.create category: "Lab Test",  description: "CADMIUM, BLOOD"
	 OrderType.create category: "Lab Test",  description: "CADMIUM, URINE"
	 OrderType.create category: "Lab Test",  description: "CAFFEINE"
	 OrderType.create category: "Lab Test",  description: "CALCIFEDIOL"
	 OrderType.create category: "Lab Test",  description: "CALCITONIN"
	 OrderType.create category: "Lab Test",  description: "CALCIUM"
	 OrderType.create category: "Lab Test",  description: "CALCIUM, IONIZED"
	 OrderType.create category: "Lab Test",  description: "CALCIUM, 24 HR URINE"
	 OrderType.create category: "Lab Test",  description: "CALCIUM, RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "CANCER ANTIGEN BREAST; (CA 15-3), (CA 27,29)"
	 OrderType.create category: "Lab Test",  description: "CANCER ANTIGEN - GI; (CA 19-9)"
	 OrderType.create category: "Lab Test",  description: "CANCER ANTIGEN - 125; (CA 125)"
	 OrderType.create category: "Lab Test",  description: "CANDIDA ANTIBODY (ID)"
	 OrderType.create category: "Lab Test",  description: "CANNABINOIDS, SERUM"
	 OrderType.create category: "Lab Test",  description: "CARBAMAZEPINE (TEGRETOL)"
	 OrderType.create category: "Lab Test",  description: "CARBAMAZEPINE EPOXIDE"
	 OrderType.create category: "Lab Test",  description: "CARBAMAZEPINE, FREE"
	 OrderType.create category: "Lab Test",  description: "CARBON DIOXIDE (CO2)"
	 OrderType.create category: "Lab Test",  description: "CARCINOEMBRYONIC ANTEGEN (CEA)"
	 OrderType.create category: "Lab Test",  description: "CARDIOLIPIN AB IGG/IGM/IGE"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "CARNITINE FREE AND TOTAL"
	 OrderType.create category: "Lab Test",  description: "CARNITINE FREE"
	 OrderType.create category: "Lab Test",  description: "CATECHOLAMINES QUANT; EPINEPHRINE, NOREPINEPHRINE"
	 OrderType.create category: "Lab Test",  description: "CATHETER TIP CULTURE"
	 OrderType.create category: "Lab Test",  description: "COMPLETE BLOOD COUNT (CBC) WITH DIFFERENTIAL"
	 OrderType.create category: "Lab Test",  description: "CD 4 / 8 LYMPHOCYTE PHENOTYPING"
	 OrderType.create category: "Lab Test",  description: "CEA (CARCINOEMBRYONIC AG)"
	 OrderType.create category: "Lab Test",  description: "CELL BLOCK"
	 OrderType.create category: "Lab Test",  description: "CELL COUNT, BODY FLUID"
	 OrderType.create category: "Lab Test",  description: "CELL COUNT, CSF"
	 OrderType.create category: "Lab Test",  description: "CELONTIN"
	 OrderType.create category: "Lab Test",  description: "CERULOPLASMIN"
	 OrderType.create category: "Lab Test",  description: "CERVICAL/VAGINAL SMEAR"
	 OrderType.create category: "Lab Test",  description: "CH50 COMPLEMENT"
	 OrderType.create category: "Lab Test",  description: "CHLAMYDIA AB IGG"
	 OrderType.create category: "Lab Test",  description: "CHLAMYDIA AB IGM"
	 OrderType.create category: "Lab Test",  description: "CHLAMYDIA BY DFA"
	 OrderType.create category: "Lab Test",  description: "CHLAMYDIA BY DNA PROBE"
	 OrderType.create category: "Lab Test",  description: "CHLAMYDIA BY APTIMA MEDIA"
	 OrderType.create category: "Lab Test",  description: "CHLAMYDIA BY LCR"
	 OrderType.create category: "Lab Test",  description: "CHLAMYDIA CULTURE"
	 OrderType.create category: "Lab Test",  description: "CHLORIDE, BODY FLUID"
	 OrderType.create category: "Lab Test",  description: "CHLORIDE, CSF"
	 OrderType.create category: "Lab Test",  description: "CHLORIDE, NASAL SECRETIONS"
	 OrderType.create category: "Lab Test",  description: "CHLORIDE, SERUM"
	 OrderType.create category: "Lab Test",  description: "CHLORIDE, 24 HR URINE"
	 OrderType.create category: "Lab Test",  description: "CHLORIDE, RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "CHLORPROMAZINE"
	 OrderType.create category: "Lab Test",  description: "CHOLESTEROL"
	 OrderType.create category: "Lab Test",  description: "CHOLINESTERASE; RBC"
	 OrderType.create category: "Lab Test",  description: "CHROMOSOME AMNIOTIC FLUID"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "CHROMOSOME ANALYSIS, BLOOD"
	 OrderType.create category: "Lab Test",  description: "CHROMOSOME ANALYSIS, EXTENDED BANDING (HIGH RESOLUTION)"
	 OrderType.create category: "Lab Test",  description: "CHROMOSOME BONE MARROW"
	 OrderType.create category: "Lab Test",  description: "CHROMOSOME CHORIONIC VILLI"
	 OrderType.create category: "Lab Test",  description: "CHROMOSOME FISH; FISH FOR ANY TEST NOT LISTED UNDER MCD"
	 OrderType.create category: "Lab Test",  description: "CHROMOSOME MCD; FISH FOR DIGEORGE, VCF, CRI-DU-CHAT, WILLIAMS, ANGELMAN'S, MILLER DIEKER, SMITH MAGENIS, AND PRADER-WILLI"
	 OrderType.create category: "Lab Test",  description: "CHROMOSOME MOSIAC"
	 OrderType.create category: "Lab Test",  description: "CHROMOSOME PRODUCT OF CONCEPTION"
	 OrderType.create category: "Lab Test",  description: "CIDAL, SERUM (SCHLICTER TEST)"
	 OrderType.create category: "Lab Test",  description: "CLONAZEPAM (CLONOPIN)"
	 OrderType.create category: "Lab Test",  description: "CLONOPIN"
	 OrderType.create category: "Lab Test",  description: "CLORZEPATE ASSAYED AS NORDIAZEPAM"
	 OrderType.create category: "Lab Test",  description: "CLOSTRIDIUM DIFFICILE TOXIN"
	 OrderType.create category: "Lab Test",  description: "CMV AB (IGG AND/OR IGM)"
	 OrderType.create category: "Lab Test",  description: "CMV AB TOTAL"
	 OrderType.create category: "Lab Test",  description: "CMV AB, IGG"
	 OrderType.create category: "Lab Test",  description: "CMV AB, IGM"
	 OrderType.create category: "Lab Test",  description: "CMV BY PCR"
	 OrderType.create category: "Lab Test",  description: "CMV CULTURE, BUFFY COAT CULTURE"
	 OrderType.create category: "Lab Test",  description: "CMV CULTURE, URINE"
	 OrderType.create category: "Lab Test",  description: "CMV - IGG"
	 OrderType.create category: "Lab Test",  description: "CMV - IGM"
	 OrderType.create category: "Lab Test",  description: "COCCI - CF -   CSF"
	 OrderType.create category: "Lab Test",  description: "COCCI - CF - PAPA"
	 OrderType.create category: "Lab Test",  description: "COCCI SEROLOGY (CF / ID)"
	 OrderType.create category: "Lab Test",  description: "COCCIDIODES - EIA SERUM"
	 OrderType.create category: "Lab Test",  description: "COLONY CT"
	 OrderType.create category: "Lab Test",  description: "COLD AGGLUTININ"
	 OrderType.create category: "Lab Test",  description: "COLONIC BRUSH - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "COLORADO TICK FEVER"
	 OrderType.create category: "Lab Test",  description: "COMPLEMENT; C-3 AND C-4"
	 OrderType.create category: "Lab Test",  description: "COMPLEMENT - CH-50 (RECOMMENDATIONS ARE TO ONLY RUN CH50, CH100 IS STILL AVAILABLE)"
	 OrderType.create category: "Lab Test",  description: "COMPREHENSIVE DRUG SCREEN; AMPHETAMINES, ANALGESICS, ANTIDEPRESSANTS, ANTIHISTAMINES, BARBITUATES, BENSODIAZEPINES, CARDIACS, MISC AGENTS, NARCOTICS, PHENOTHIAZINES, SEDATIVES AND HYPNOTICS, VOLATILES"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "COMPREHENSIVE METABOLIC PANEL   (CMP); ALBUMIN, ALKALINE PHOSPHATASE (ALP), AST (SGOT), ALT (SGPT), BILIRUBIN (TOTAL), BUN, CALCIUM, CO2, CHLORIDE, CREATININE, POTASSIUM, SODIUM, TOTAL PROTEIN"
	 OrderType.create category: "Lab Test",  description: "COPPER, SERUM"
	 OrderType.create category: "Lab Test",  description: "COPPER, URINE"
	 OrderType.create category: "Lab Test",  description: "CORD BLOOD;  ABO, DIRECT ANTIGLOBULIN, RH"
	 OrderType.create category: "Lab Test",  description: "CORTISOL"
	 OrderType.create category: "Lab Test",  description: "CORTISOL, URINE"
	 OrderType.create category: "Lab Test",  description: "CORTISOL, FREE - URINE"
	 OrderType.create category: "Lab Test",  description: "COXSACKIE A; SEROTYPES 7,9,10,16"
	 OrderType.create category: "Lab Test",  description: "COXSACKIE B; SEROTYPES 1,2,3,4,5,6"
	 OrderType.create category: "Lab Test",  description: "C-PEPTIDE (SERUM)"
	 OrderType.create category: "Lab Test",  description: "CPK"
	 OrderType.create category: "Lab Test",  description: "CPK/CK-MB ISOENZYME"
	 OrderType.create category: "Lab Test",  description: "CREATINE"
	 OrderType.create category: "Lab Test",  description: "CREATINE, URINE"
	 OrderType.create category: "Lab Test",  description: "CREATININE"
	 OrderType.create category: "Lab Test",  description: "CREATININE, CLEARANCE"
	 OrderType.create category: "Lab Test",  description: "CREATININE, RANDOM"
	 OrderType.create category: "Lab Test",  description: "CREATININE, URINE - 24 HOUR"
	 OrderType.create category: "Lab Test",  description: "CROSSMATCH"
	 OrderType.create category: "Lab Test",  description: "CRP, HIGHLY SENSITIVE"
	 OrderType.create category: "Lab Test",  description: "CRYOGLOBULIN"
	 OrderType.create category: "Lab Test",  description: "CRYPTOCOCCUS AG, BLOOD"
	 OrderType.create category: "Lab Test",  description: "CRYPTOCOCCUS AG, CSF"
	 OrderType.create category: "Lab Test",  description: "CRYPTOSPORIDIA / GIARDIA"
	 OrderType.create category: "Lab Test",  description: "CSF - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "CSF FUNGUS CULTURE +  INDIA INK"
	 OrderType.create category: "Lab Test",  description: "CSF CULTURE + GRAM"
	 OrderType.create category: "Lab Test",  description: "CULTURE - BONE BANK"
	 OrderType.create category: "Lab Test",  description: "CULTURE - TRANS RX"
	 OrderType.create category: "Lab Test",  description: "CYANIDE (NOT FOR NITROPRUSSIDE MONITORING)"
	 OrderType.create category: "Lab Test",  description: "CYCLIC AMP, NEPHROGENOUS"
	 OrderType.create category: "Lab Test",  description: "CYCLIC AMP, PLASMA"
	 OrderType.create category: "Lab Test",  description: "CYCLIC AMP URINE"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "CYCLOSPORIN"
	 OrderType.create category: "Lab Test",  description: "CYCLOSPORIN BY HPLC"
	 OrderType.create category: "Lab Test",  description: "CYLEX - IMMUNO"
	 OrderType.create category: "Lab Test",  description: "CYSTIC FLUID - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "CYSTICEROSIS , BLOOD"
	 OrderType.create category: "Lab Test",  description: "CYSTICEROSIS , CSF"
	 OrderType.create category: "Lab Test",  description: "CYSTINE PLASMA QUANT"
	 OrderType.create category: "Lab Test",  description: "CYSTINE URINE QUANT"
	 OrderType.create category: "Lab Test",  description: "CYTOGENETICS TESTING (LIST FOLLOWS) CHR AF"
	 OrderType.create category: "Lab Test",  description: "CHR BL CHR EB"
	 OrderType.create category: "Lab Test",  description: "CHR MOS"
	 OrderType.create category: "Lab Test",  description: "CHR CVS CHR POC"
	 OrderType.create category: "Lab Test",  description: "CHR ST CHR BM"
	 OrderType.create category: "Lab Test",  description: "CHR LB"
	 OrderType.create category: "Lab Test",  description: "CHR LN"
	 OrderType.create category: "Lab Test",  description: "CHR TC SKN; OSTEOGENESIS IMPERFECTA OR PYRUVATE DEFICIENCY"
	 OrderType.create category: "Lab Test",  description: "CHR MCD CHR FISH"
	 OrderType.create category: "Lab Test",  description: "CYTOLOGY FOR ACCUR"
	 OrderType.create category: "Lab Test",  description: "CYTOMEGALIC INCLUSION BODIES"
	 OrderType.create category: "Lab Test",  description: "CYTOMEGALOVIRUS AB TOTAL"
	 OrderType.create category: "Lab Test",  description: "CYTOMEGALOVIRUS BY PCR"
	 OrderType.create category: "Lab Test",  description: "CYTOMEGALOVIRUS IGG"
	 OrderType.create category: "Lab Test",  description: "CYTOMEGALOVIRUS IGG AND/OR IGM"
	 OrderType.create category: "Lab Test",  description: "CYTOMEGALOVIRUS IGM"
	 OrderType.create category: "Lab Test",  description: "D-DIMER"
	 OrderType.create category: "Lab Test",  description: "DEHYDROEPIANDROSTERONE SULFATE (DHEA, SULFATE)"
	 OrderType.create category: "Lab Test",  description: "DEHYDROEPIANDROSTERONE (DHEA)"
	 OrderType.create category: "Lab Test",  description: "DEHYDROEPIANDROSTERONE (DHEA, URINE)"
	 OrderType.create category: "Lab Test",  description: "DELTA OD"
	 OrderType.create category: "Lab Test",  description: "DENGUE FEVER"
	 OrderType.create category: "Lab Test",  description: "11 - DEOXYCORTISOL"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "DEPEKENE (VALPROIC ACID)"
	 OrderType.create category: "Lab Test",  description: "DESIPRAMINE`"
	 OrderType.create category: "Lab Test",  description: "DHEA"
	 OrderType.create category: "Lab Test",  description: "DHEA SULFATE"
	 OrderType.create category: "Lab Test",  description: "DIAMOX (ACETAZOLAMIDE)"
	 OrderType.create category: "Lab Test",  description: "DIC SCREEN; PT, PTT; HEMOGRAM; FIBRIN SPLIT PRODUCTS"
	 OrderType.create category: "Lab Test",  description: "DIGITOXIN"
	 OrderType.create category: "Lab Test",  description: "DIGOXIN"
	 OrderType.create category: "Lab Test",  description: "5 - a - DIHYDROTESTOSTERONE"
	 OrderType.create category: "Lab Test",  description: "DILANTIN (PHENYTOIN)"
	 OrderType.create category: "Lab Test",  description: "DIPHTHERIA/TETANUS AB"
	 OrderType.create category: "Lab Test",  description: "DIRECT COOMBS - ANTIGLOBULIN"
	 OrderType.create category: "Lab Test",  description: "DISOPYRAMINE (NORPACE)"
	 OrderType.create category: "Lab Test",  description: "DNA AB QUANT"
	 OrderType.create category: "Lab Test",  description: "DNA APOLIPOPROTEIN E"
	 OrderType.create category: "Lab Test",  description: "DNA DUCHENNE-MUSCULAR DYSTROPHY"
	 OrderType.create category: "Lab Test",  description: "DNA FACTOR V (LEIDENS)"
	 OrderType.create category: "Lab Test",  description: "DNA FRAGILE X"
	 OrderType.create category: "Lab Test",  description: "DNA HIV-1 QUANT"
	 OrderType.create category: "Lab Test",  description: "DNA HUNTINGTONS"
	 OrderType.create category: "Lab Test",  description: "DNA KENNEDY DISEASE"
	 OrderType.create category: "Lab Test",  description: "DNA MELAS/MITOCHON"
	 OrderType.create category: "Lab Test",  description: "DNA MYOTONIC DYSTROPHY"
	 OrderType.create category: "Lab Test",  description: "DNA PROTHROMBIN G202IDA GENE"
	 OrderType.create category: "Lab Test",  description: "DNASE-B AB"
	 OrderType.create category: "Lab Test",  description: "DRUG ABUSE PANEL - STAT URINE; AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, COCAINE METABOLITE, MARIJUANA, OPIATES, PHENCYLIDINE, TRICYCLIC ANTEDEPRESSANTS"
	 OrderType.create category: "Lab Test",  description: "DRUG PANEL - 7 NEWBORN MECONIUM; AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE 150, OPIATES, PHENCYCLIDINE"
	 OrderType.create category: "Lab Test",  description: "DRUG PANEL - 7 URINE; AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE 150, OPIATES, PHENCYCLIDINE"
	 OrderType.create category: "Lab Test",  description: "DRUG PANEL - 7A  URINE; ALCOHOL, AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE 150, OPIATES, PHENCYCLIDINE"
	 OrderType.create category: "Lab Test",  description: "DRUG PANEL - 9A  URINE  TRAUMA OR OTHER; ALCOHOL, AMPHETAMINES, BARBITUATES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE"
	 OrderType.create category: "Lab Test",  description: "300, OPIATES, PHENCYCLIDINE, PROPOXYPHENE"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "DRUG SCREEN BLOOD AND URINE; AMPHETAMINES-URINE, BARBITUATES-URINE, BENZODIAZEPINES-URINE, CANNABINOIDS(THC)- URINE,                 COCAINE-URINE, OPIATES-URINE, PHENCYCLIDINE-URINE, TRICYCLICS-URINE, ACETOMENOPHEN-SERUM, SALICYLATES-SERUM, ALCOHOL-SERUM"
	 OrderType.create category: "Lab Test",  description: "DUODENAL SECRETIONS - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "EBV AB"
	 OrderType.create category: "Lab Test",  description: "ECHINOCOCCUS SERO"
	 OrderType.create category: "Lab Test",  description: "ECHOVIRUS SERO"
	 OrderType.create category: "Lab Test",  description: "ELAVIL (AMITRIPTYLINE)"
	 OrderType.create category: "Lab Test",  description: "ELECTROLYTES;  CO2, CHLORIDE, POTASSIUM, SODIUM"
	 OrderType.create category: "Lab Test",  description: "ELECTROLYTES - FLUID; CHLORIDE-FLUID, POTASSIUM-FLUID, SODIUM-FLUID"
	 OrderType.create category: "Lab Test",  description: "ELECTROLYTES - RANDOM URINE; CHLORIDE- RANDOM; POTASSIUM-RANDOM; SODIUM-RANDOM"
	 OrderType.create category: "Lab Test",  description: "ELECTROLYTES - 24 HOUR URINE; CHLORIDE-24"
	 OrderType.create category: "Lab Test",  description: "HOUR; POTASSIUM-24 HOUR; SODIUM-24 HOUR"
	 OrderType.create category: "Lab Test",  description: "ELECTRON MICROSCOPY"
	 OrderType.create category: "Lab Test",  description: "ELECTROPHORESIS, PROTEIN; 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "ELECTROPHORESIS, PROTEIN - SERUM; ALBUMIN, ALPHA-1, ALPHA-2, BETA, GAMMA"
	 OrderType.create category: "Lab Test",  description: "ELECTROPHORESIS, RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "ELECTROPHORESIS, 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "ELUTION, WITH ANTIBODY IDENTIFICATION"
	 OrderType.create category: "Lab Test",  description: "ENCEPHALITIS AB PANEL; CALIFORNIA ENCEPHALITIS, EAST EQUINE ENCEPHALITIS, ST.LOIUS ENCEPHALITIS, WESTERN ENCEPHALITIS"
	 OrderType.create category: "Lab Test",  description: "ENDOMETRIAL ASPIRATE - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "ENDOMYSIAL AB, IGA"
	 OrderType.create category: "Lab Test",  description: "EOSINOPHIL COUNT, ABSOLUTE"
	 OrderType.create category: "Lab Test",  description: "EPIDERMAL (SKIN) AB"
	 OrderType.create category: "Lab Test",  description: "EPINEPHERINE"
	 OrderType.create category: "Lab Test",  description: "EPSTEIN-BARR VIRUS PANEL;  ANTIEARLY AG, ANTINUCLEAR AG, ANTI VCA-IGG, ANTI VCA-IGM"
	 OrderType.create category: "Lab Test",  description: "ERYTHROPOIETIN"
	 OrderType.create category: "Lab Test",  description: "ESOPHAGEAL BRUSH - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "ESR (SEDIMENTATION RATE)"
	 OrderType.create category: "Lab Test",  description: "ESTERASE STAIN, SPECIFIC"
	 OrderType.create category: "Lab Test",  description: "ESTRADIOL - SERUM"
	 OrderType.create category: "Lab Test",  description: "ESTRADIOL -  URINE"
	 OrderType.create category: "Lab Test",  description: "ESTROGEN RECEPTORS"
	 OrderType.create category: "Lab Test",  description: "ESTROGEN URINE FRACTIONATED"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "ESTRONE, SERUM"
	 OrderType.create category: "Lab Test",  description: "ESTRONE, URINE"
	 OrderType.create category: "Lab Test",  description: "ETHOSUXIMIDE"
	 OrderType.create category: "Lab Test",  description: "ETHYLENE GLYCOL"
	 OrderType.create category: "Lab Test",  description: "EUGLOBULIN LYSIS TIME"
	 OrderType.create category: "Lab Test",  description: "FACTOR (2) II (PROTHROMBIN)"
	 OrderType.create category: "Lab Test",  description: "FACTOR 2 BY PCR"
	 OrderType.create category: "Lab Test",  description: "FACTOR (5) V ASSAY"
	 OrderType.create category: "Lab Test",  description: "FACTOR (5) V LEIDEN BY PCR"
	 OrderType.create category: "Lab Test",  description: "FACTOR (7) VII ASSAY"
	 OrderType.create category: "Lab Test",  description: "FACTOR (8) VIII ASSAY"
	 OrderType.create category: "Lab Test",  description: "FACTOR (8) VIII:C"
	 OrderType.create category: "Lab Test",  description: "FACTOR (9) IX ASSAY"
	 OrderType.create category: "Lab Test",  description: "FACTOR (10) X ASSAY"
	 OrderType.create category: "Lab Test",  description: "FACTOR (11) XI"
	 OrderType.create category: "Lab Test",  description: "FACTOR (12) XII"
	 OrderType.create category: "Lab Test",  description: "FACTOR (13) XIII"
	 OrderType.create category: "Lab Test",  description: "FAT STAIN - STOOL  (QUALITATIVE)"
	 OrderType.create category: "Lab Test",  description: "FAT STOOL (QUANT)"
	 OrderType.create category: "Lab Test",  description: "FATTY ACIDS, FREE"
	 OrderType.create category: "Lab Test",  description: "FDP"
	 OrderType.create category: "Lab Test",  description: "FEBRILE AGGLUTINATIONS; BRUCELLA; PARATYPHOID A,B,C; PROTEUS OX K,2,19; SALMONELLA A,B,C,E; TULAREMIA; TYPHOID O"
	 OrderType.create category: "Lab Test",  description: "FELBAMATE"
	 OrderType.create category: "Lab Test",  description: "FERRITIN"
	 OrderType.create category: "Lab Test",  description: "FETAL FIBRONECTIN"
	 OrderType.create category: "Lab Test",  description: "FETAL HEMOGLOBIN"
	 OrderType.create category: "Lab Test",  description: "FETAL RBC - STAIN (KBS)"
	 OrderType.create category: "Lab Test",  description: "FETAL SCREEN - RHIG"
	 OrderType.create category: "Lab Test",  description: "FIBRIN DEGREDATION PRODUCTS     (FDP)"
	 OrderType.create category: "Lab Test",  description: "FIBRINOGEN"
	 OrderType.create category: "Lab Test",  description: "FINE NEEDLE ASPIRATION"
	 OrderType.create category: "Lab Test",  description: "FK506   (TACROLIMUS)"
	 OrderType.create category: "Lab Test",  description: "FLUID CELL COUNT"
	 OrderType.create category: "Lab Test",  description: "FLECAINIDE"
	 OrderType.create category: "Lab Test",  description: "FLUOXETINE (PROZAC)"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "FLUPHENAZINE"
	 OrderType.create category: "Lab Test",  description: "FOLATE"
	 OrderType.create category: "Lab Test",  description: "FOLATE; RBC"
	 OrderType.create category: "Lab Test",  description: "FOSPHENYTOIN"
	 OrderType.create category: "Lab Test",  description: "FREE DILANTIN;  %FREE DILANTIN; TOTAL DILANTIN"
	 OrderType.create category: "Lab Test",  description: "FREE ERYTHROCYTE PORPH"
	 OrderType.create category: "Lab Test",  description: "FREE T3"
	 OrderType.create category: "Lab Test",  description: "FREE T4"
	 OrderType.create category: "Lab Test",  description: "FREE TEGRETOL"
	 OrderType.create category: "Lab Test",  description: "FROZEN SECTION"
	 OrderType.create category: "Lab Test",  description: "FSH - SERUM"
	 OrderType.create category: "Lab Test",  description: "FSH -  URINE"
	 OrderType.create category: "Lab Test",  description: "FSP"
	 OrderType.create category: "Lab Test",  description: "FTA MHA/TP- SERUM"
	 OrderType.create category: "Lab Test",  description: "FTA MHA/TP-CSF"
	 OrderType.create category: "Lab Test",  description: "FUNGAL BLOOD CULTURE"
	 OrderType.create category: "Lab Test",  description: "FUNGUS CULTURE"
	 OrderType.create category: "Lab Test",  description: "FUNGUS PANEL - CF; ASPERGILLUS CF; BLASTOMYCES CF; COCCIDIODES; HISTOPLASMA CF; MYCELIAL PHASE-HISTO;                        YEAST PHASE-HISTO"
	 OrderType.create category: "Lab Test",  description: "G 6 PD SCREEN"
	 OrderType.create category: "Lab Test",  description: "G 6 PD QUANT"
	 OrderType.create category: "Lab Test",  description: "GABAPENTIN (NEURONTIN)"
	 OrderType.create category: "Lab Test",  description: "GAMMA GLOBULIN IGG, CSF"
	 OrderType.create category: "Lab Test",  description: "GAMMA GLUTAMYL TRANSFERASE (GGT)"
	 OrderType.create category: "Lab Test",  description: "GASTRIC CULTURE AND GRAM STAIN"
	 OrderType.create category: "Lab Test",  description: "GASTRIC BRUSH - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "GASTRIC WASHINGS - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "GASTRIN"
	 OrderType.create category: "Lab Test",  description: "GBM (GLOMERULAR BASEMENT) AB,IGA/IGG"
	 OrderType.create category: "Lab Test",  description: "GC SCREEN"
	 OrderType.create category: "Lab Test",  description: "GENERAL HEALTH PANEL; CMP, CBC, TSH"
	 OrderType.create category: "Lab Test",  description: "GENITAL CULT + GRAM"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "GENITAL CULT + GRAM + ANAEROBE"
	 OrderType.create category: "Lab Test",  description: "GENITAL CULTURE"
	 OrderType.create category: "Lab Test",  description: "GENITAL STREP B"
	 OrderType.create category: "Lab Test",  description: "GENTAMICIN"
	 OrderType.create category: "Lab Test",  description: "GENPROBE FOR CHLAMYDIA AND/OR GC"
	 OrderType.create category: "Lab Test",  description: "GLIADIN AB, IGG AND IGA"
	 OrderType.create category: "Lab Test",  description: "GLOMERULAR BASEMENT AB, IGA/IGG"
	 OrderType.create category: "Lab Test",  description: "GLUCAGON"
	 OrderType.create category: "Lab Test",  description: "GLUCOLA"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE -  CSF"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE -  FLUID"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE -  QUANTITATIVE (24 HR)"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE -  RANDOM"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE - SEMIQUANT (CLINITEST)"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE -  ONE HOUR PP"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE -  TWO HOUR PP"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE TOLERANCE TEST -  1 HOUR; GLUCOSE- FASTING AND 1 HOUR"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE TOLERANCE TEST -  2 HOURS; GLUCOSE-FASTING, 1 AND 2 HOUR"
	 OrderType.create category: "Lab Test",  description: "GLUCOSE TOLERANCE TEST -  3 HOURS; GLUCOSE-FASTING, 1,2 AND 3 HOURS"
	 OrderType.create category: "Lab Test",  description: "GLYCOSYLATED HEMOGLOBIN (A1C)"
	 OrderType.create category: "Lab Test",  description: "GM1 AB PANEL"
	 OrderType.create category: "Lab Test",  description: "GOLD"
	 OrderType.create category: "Lab Test",  description: "GONOCOCCAL ANTIBODIES"
	 OrderType.create category: "Lab Test",  description: "GONORRHEA BY DNA PROBE (GENPROBE)"
	 OrderType.create category: "Lab Test",  description: "GONORRHEA PROBE BY LCR"
	 OrderType.create category: "Lab Test",  description: "GRAM STAIN"
	 OrderType.create category: "Lab Test",  description: "GRAM STAIN BUFFY COAT"
	 OrderType.create category: "Lab Test",  description: "GROSS CONSULTATION"
	 OrderType.create category: "Lab Test",  description: "GROWTH HORMONE"
	 OrderType.create category: "Lab Test",  description: "H. PYLORI AB IGG"
	 OrderType.create category: "Lab Test",  description: "HAA (HEPATITIS A AB; IGM)"
	 OrderType.create category: "Lab Test",  description: "HALDOL"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "HALOPERIDOL (HALDOL)"
	 OrderType.create category: "Lab Test",  description: "HAM TEST (ACID HEMOLYSIN)"
	 OrderType.create category: "Lab Test",  description: "HAPTOGLOBIN"
	 OrderType.create category: "Lab Test",  description: "HCG, QUALITATIVE"
	 OrderType.create category: "Lab Test",  description: "HCG, QUANTITATIVE"
	 OrderType.create category: "Lab Test",  description: "HDL CHOLESTEROL"
	 OrderType.create category: "Lab Test",  description: "HEAVY METALS SCREEN, BLOOD; ARSENIC, LEAD, MERCURY"
	 OrderType.create category: "Lab Test",  description: "HEAVY METALS SCREEN, URINE"
	 OrderType.create category: "Lab Test",  description: "ARSENIC, LEAD, MERCURY"
	 OrderType.create category: "Lab Test",  description: "HELICOBACTER CULTURE"
	 OrderType.create category: "Lab Test",  description: "HELICOBACTER PYLORII AB"
	 OrderType.create category: "Lab Test",  description: "HEMOGLOBIN PLASMA"
	 OrderType.create category: "Lab Test",  description: "HEMOGLOBIN, SERUM"
	 OrderType.create category: "Lab Test",  description: "HEMOGLOBIN A1C; (GLYCOSALATED HGB)"
	 OrderType.create category: "Lab Test",  description: "HEMOGLOBIN ELECTROPHORESIS"
	 OrderType.create category: "Lab Test",  description: "HEMOGLOBIN S"
	 OrderType.create category: "Lab Test",  description: "HEMOGRAM;  HCT, HGB, MCH, MCV, MCHC, RDW, RBC, WBC, PLATELETS"
	 OrderType.create category: "Lab Test",  description: "HEMOPHILUS INFLUENZA TYPE B - BAS; (H INF TYPE B - BAS)"
	 OrderType.create category: "Lab Test",  description: "HEMOSIDERIN"
	 OrderType.create category: "Lab Test",  description: "HEPARIN ANTI-Xa LMWH"
	 OrderType.create category: "Lab Test",  description: "HEPARIN ANTI-Xa UNFRACT"
	 OrderType.create category: "Lab Test",  description: "HEPARIN INDUCED THROMBOCYTOPENIA (HIT)"
	 OrderType.create category: "Lab Test",  description: "HEPATIC FUNTION PANEL (LIVER PANEL)"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS A AB (TOTAL)"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS A ANTIBODY- IGM"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS B CORE ANTIBODY- IGG"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS B CORE ANTIBODY-IGM"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS B SURFACE ANTIBODY"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS B SURFACE ANTIGEN"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS BE ANTIBODY"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS BE ANTIGEN"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS C ANTIBODY"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS C RNA, QUANT"
	 OrderType.create category: "Lab Test",  description: "HEPATITIS DELTA AB"
	 OrderType.create category: "Lab Test",  description: "HERPES IGG AB SIMPLEX (I  AND II)"
	 OrderType.create category: "Lab Test",  description: "HERPES SIMPLEX IGM AB"
	 OrderType.create category: "Lab Test",  description: "HERPES CULTURE"
	 OrderType.create category: "Lab Test",  description: "HERPES DFA"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "HERPES IGM ANTIBODIES"
	 OrderType.create category: "Lab Test",  description: "HERPES SIMPLEX VIRUS BY PCR, SERUM"
	 OrderType.create category: "Lab Test",  description: "HERPES SIMPLEX VIRUS BY PCR, CSF"
	 OrderType.create category: "Lab Test",  description: "HERPES VS VARICELLA CULTURE"
	 OrderType.create category: "Lab Test",  description: "HEXOSAMINIDASE A; REFER TO TAY SACHS"
	 OrderType.create category: "Lab Test",  description: "HIGH DENSITY LIPOPROTEIN CHOL"
	 OrderType.create category: "Lab Test",  description: "HIPPURIC ACID"
	 OrderType.create category: "Lab Test",  description: "HISTOPLASMA AB; MYCELIAL AND YEAST PHASE"
	 OrderType.create category: "Lab Test",  description: "HIV - REFER TO HUMAN IMMUNODEFICIENCY VIRUS"
	 OrderType.create category: "Lab Test",  description: "HIV RAPID SCREEN"
	 OrderType.create category: "Lab Test",  description: "HIV-1 AB WESTERN BLOT"
	 OrderType.create category: "Lab Test",  description: "HIV-1 DNA BRANCH CHAIN"
	 OrderType.create category: "Lab Test",  description: "HIV-1 DNA QUAL BY PCR"
	 OrderType.create category: "Lab Test",  description: "HIV-1 P24 ANTIGEN"
	 OrderType.create category: "Lab Test",  description: "HIV-1 RNA"
	 OrderType.create category: "Lab Test",  description: "HIV-1 RNA QUANT BY PCR"
	 OrderType.create category: "Lab Test",  description: "HIV-1 ULTRA SENSITIVE RNA BY PCR"
	 OrderType.create category: "Lab Test",  description: "HLA A,B,C PHENOTYPE"
	 OrderType.create category: "Lab Test",  description: "HLA AB DETECTION"
	 OrderType.create category: "Lab Test",  description: "HLA -  B27"
	 OrderType.create category: "Lab Test",  description: "HLA - TYPING A-B-C"
	 OrderType.create category: "Lab Test",  description: "HLA TYPING, DR / DQ PHENOTYPE"
	 OrderType.create category: "Lab Test",  description: "HOMOCYSTINE"
	 OrderType.create category: "Lab Test",  description: "HOMOCYSTINE, URINE"
	 OrderType.create category: "Lab Test",  description: "HOMOVANILLIC ACID"
	 OrderType.create category: "Lab Test",  description: "HU (NEURONAL NUCLEAR AB)"
	 OrderType.create category: "Lab Test",  description: "HUMAN GROWTH HORMONE"
	 OrderType.create category: "Lab Test",  description: "HUMAN PLACENTAL LACTOGEN"
	 OrderType.create category: "Lab Test",  description: "HYDROXYPROLINE TOTAL"
	 OrderType.create category: "Lab Test",  description: "HYDROXYPROLINE; FREE ANDTOTAL HYDROXYPROLINE"
	 OrderType.create category: "Lab Test",  description: "IGA, SERUM (IMMUNOGLOBULIN A)"
	 OrderType.create category: "Lab Test",  description: "IGD, SERUM (IMMUNOGLOBULIN D)"
	 OrderType.create category: "Lab Test",  description: "IGE-SERUM (IMMUNOGLOBULIN E)"
	 OrderType.create category: "Lab Test",  description: "IGE TOTAL (IMMUNOGLOBULIN E)"
	 OrderType.create category: "Lab Test",  description: "IGF - BINDING PROTEIN 3"
	 OrderType.create category: "Lab Test",  description: "IGG-SERUM (IMMUNOGLOBULIN G, SERUM)"
	 OrderType.create category: "Lab Test",  description: "IGG - CSF (IMMUNOGLOBULIN G, CSF)"
	 OrderType.create category: "Lab Test",  description: "IGG SUBCLASSES"
	 OrderType.create category: "Lab Test",  description: "IGG SYNTHESIS RATE; ALBUMIN INDEX, ALBUMIN SERUM, CSF IGG INDEX, IGG CSF"
	 OrderType.create category: "Lab Test",  description: "IGM-SERUM (IMMUNOGLOBULIN M, SERUM)"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "IMIPRAMINE, TOTAL"
	 OrderType.create category: "Lab Test",  description: "IMMUNE COMPLEX"
	 OrderType.create category: "Lab Test",  description: "IMMUNOELECTROPHORESIS"
	 OrderType.create category: "Lab Test",  description: "IMMUNOELECTROPHORESIS, RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "IMMUNOELECTROPHORESIS, 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "IMMUNOGLOBULINS IGG, IGA, IGM"
	 OrderType.create category: "Lab Test",  description: "IMMUNOGLOBULIN A"
	 OrderType.create category: "Lab Test",  description: "IMMUNOGLOBULIN G"
	 OrderType.create category: "Lab Test",  description: "IMMUNOGLOBULIN M"
	 OrderType.create category: "Lab Test",  description: "IMMUNOGLOBULIN, IgE TOTAL"
	 OrderType.create category: "Lab Test",  description: "INDERAL (PROPRANOLOL)"
	 OrderType.create category: "Lab Test",  description: "INDIA INK"
	 OrderType.create category: "Lab Test",  description: "INFECTIOUS MONONUCLEOSIS"
	 OrderType.create category: "Lab Test",  description: "INFLUENZA A ANTIBODIES, CF"
	 OrderType.create category: "Lab Test",  description: "INFLUENZA B ANTIBODIES, CF"
	 OrderType.create category: "Lab Test",  description: "INHIBITOR STUDIES - PT"
	 OrderType.create category: "Lab Test",  description: "INHIBITOR STUDIES - PTT"
	 OrderType.create category: "Lab Test",  description: "INSULIN"
	 OrderType.create category: "Lab Test",  description: "INSULIN AB HUMAN"
	 OrderType.create category: "Lab Test",  description: "INSULIN LIKE GROWTH FACTOR AB (SOMATAMEDIN C)"
	 OrderType.create category: "Lab Test",  description: "INTRINSIC FACTOR ANTIBODIES"
	 OrderType.create category: "Lab Test",  description: "IONIZED CALCIUM"
	 OrderType.create category: "Lab Test",  description: "IRON"
	 OrderType.create category: "Lab Test",  description: "IRON STUDY - IRON; %SATURATION; TIBC; TRANSFERRIN"
	 OrderType.create category: "Lab Test",  description: "IRON TISSUE"
	 OrderType.create category: "Lab Test",  description: "ISLET CELL AB"
	 OrderType.create category: "Lab Test",  description: "ISOPROPANOL"
	 OrderType.create category: "Lab Test",  description: "KB STAIN (KEIHAUER BETKE)"
	 OrderType.create category: "Lab Test",  description: "KETONES, QUALITATIVE"
	 OrderType.create category: "Lab Test",  description: "KIDNEY BIOPSY"
	 OrderType.create category: "Lab Test",  description: "KLEIHAUER BETKE (FETAL RBC)"
	 OrderType.create category: "Lab Test",  description: "KLONOPIN"
	 OrderType.create category: "Lab Test",  description: "KOH WET MOUNT - FUNGUS"
	 OrderType.create category: "Lab Test",  description: "L/S RATIO"
	 OrderType.create category: "Lab Test",  description: "LACTATE (LACTIC ACID)"
	 OrderType.create category: "Lab Test",  description: "LACTATE, CSF"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "LACTOSE TOLERANCE; GLUCOSE-FASTING, 1, 2 AND 3"
	 OrderType.create category: "Lab Test",  description: "HRS"
	 OrderType.create category: "Lab Test",  description: "LAMELLAR BODY COUNT"
	 OrderType.create category: "Lab Test",  description: "LAMICTAL"
	 OrderType.create category: "Lab Test",  description: "LAMOTRIGINE (LAMICTAL)"
	 OrderType.create category: "Lab Test",  description: "LASA-P; (LIPID ASSOCIATED SIALIC ACID)"
	 OrderType.create category: "Lab Test",  description: "LATEX-SPECIFIC IGE"
	 OrderType.create category: "Lab Test",  description: "LAVAGE PROFILE"
	 OrderType.create category: "Lab Test",  description: "LDH"
	 OrderType.create category: "Lab Test",  description: "LDH ISOENZYMES"
	 OrderType.create category: "Lab Test",  description: "LDH, BODY FLUID"
	 OrderType.create category: "Lab Test",  description: "LDH, CSF"
	 OrderType.create category: "Lab Test",  description: "LDH ISOENZYMES, FRACTIONATED"
	 OrderType.create category: "Lab Test",  description: "LE PREPARATION; (LUPUS ERYTHEMATOSUS ANTIBODIES, SERUM)"
	 OrderType.create category: "Lab Test",  description: "LEAD, BLOOD"
	 OrderType.create category: "Lab Test",  description: "LEAD, URINE"
	 OrderType.create category: "Lab Test",  description: "LEGIONELLA ANTIBODIES"
	 OrderType.create category: "Lab Test",  description: "LEGIONELLA ANTIGEN"
	 OrderType.create category: "Lab Test",  description: "LEGIONELLA CULTURE"
	 OrderType.create category: "Lab Test",  description: "LEPTOSPIRA ANTIBODIES"
	 OrderType.create category: "Lab Test",  description: "LEUCINE AMINO PEPTIDASE"
	 OrderType.create category: "Lab Test",  description: "LEUKEMIA PROFILE"
	 OrderType.create category: "Lab Test",  description: "LH, SERUM; (LUTEINIZING HORMONE, SERUM)"
	 OrderType.create category: "Lab Test",  description: "LIPASE, SERUM"
	 OrderType.create category: "Lab Test",  description: "LIPID ASSO SIALIC ACID"
	 OrderType.create category: "Lab Test",  description: "LIPID PANEL; CHOLESTEROL, HDL, LDL (CALCULATED), TRIGLYCERIDES"
	 OrderType.create category: "Lab Test",  description: "LIPID PANEL EXTENDED; CHOLESTEROL, HDL, LDL (CALCULATED), TRIGLYCERIDES, CHOL/HDL, VLDL (CALCULATED)"
	 OrderType.create category: "Lab Test",  description: "LIPOPROTEIN A"
	 OrderType.create category: "Lab Test",  description: "LITHIUM, SERUM"
	 OrderType.create category: "Lab Test",  description: "LIVER KIDNEY MICROSOME AB"
	 OrderType.create category: "Lab Test",  description: "LONG CHAIN FATTY ACIDS"
	 OrderType.create category: "Lab Test",  description: "LORAZEPAM"
	 OrderType.create category: "Lab Test",  description: "LOXAPINE"
	 OrderType.create category: "Lab Test",  description: "LUNG MATURITY; (SEE L/S AND LAMELLAR BODY CT)"
	 OrderType.create category: "Lab Test",  description: "LUPUS ANTICOAGULANT"
	 OrderType.create category: "Lab Test",  description: "LYME-BORRELIA AB"
	 OrderType.create category: "Lab Test",  description: "LYMPHOGRANULOMA VENEREUM, CF"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "LYMPHOMA PROFILE"
	 OrderType.create category: "Lab Test",  description: "LYSOSOMAL ENZYME"
	 OrderType.create category: "Lab Test",  description: "MAGNESIUM"
	 OrderType.create category: "Lab Test",  description: "MAGNESIUM, RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "MAGNESIUM, 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "MALARIAL SMEAR"
	 OrderType.create category: "Lab Test",  description: "MARIJUANA, QUAL, URINE, THC"
	 OrderType.create category: "Lab Test",  description: "MEASLES (RUBELLA) AB IGG"
	 OrderType.create category: "Lab Test",  description: "MEALSES (RUBEOLA) AB IGG"
	 OrderType.create category: "Lab Test",  description: "MEASLES (RUBEOLA) AB IGM"
	 OrderType.create category: "Lab Test",  description: "MEBARAL (MEPHOBARBITAL)"
	 OrderType.create category: "Lab Test",  description: "MECONIUM DRUG PANEL; AMPHETAMINES, BENZODIAZEPINES, CANNABINOIDS(THC), COCAINE, OPIATES, PHENCYCLIDINE"
	 OrderType.create category: "Lab Test",  description: "MERCURY"
	 OrderType.create category: "Lab Test",  description: "MERCURY - URINE"
	 OrderType.create category: "Lab Test",  description: "METABOLIC SCREEN; CYCTINE, DNPH, FERRIC CHLORIDE, MPS, URINE AMINO ACIDS"
	 OrderType.create category: "Lab Test",  description: "METANEPHRINES, TOTAL"
	 OrderType.create category: "Lab Test",  description: "METHADONE"
	 OrderType.create category: "Lab Test",  description: "METHADONE, QUAL URINE"
	 OrderType.create category: "Lab Test",  description: "METHANOL"
	 OrderType.create category: "Lab Test",  description: "METHOTREXATE"
	 OrderType.create category: "Lab Test",  description: "METHSUXIMIDE / NORMETHSUXIMIDE"
	 OrderType.create category: "Lab Test",  description: "METHYLMELONIC ACID"
	 OrderType.create category: "Lab Test",  description: "METHYLMELONIC ACID - URINE"
	 OrderType.create category: "Lab Test",  description: "MEXILITINE"
	 OrderType.create category: "Lab Test",  description: "MHPG , URINE"
	 OrderType.create category: "Lab Test",  description: "MICROALBUMIN, 24 HOUR UR QUANT AND CREATININE"
	 OrderType.create category: "Lab Test",  description: "MICROALBUMIN, RANDOM UR AND CREATININE"
	 OrderType.create category: "Lab Test",  description: "MICROSOMAL AB"
	 OrderType.create category: "Lab Test",  description: "MINIMAL BACTERICIDAL CONCENTRATION"
	 OrderType.create category: "Lab Test",  description: "MISCELLANEOUS FLUID - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "MITOCHONDRIAL AB, IGG"
	 OrderType.create category: "Lab Test",  description: "MITOCHRONDRIAL ENZYME BIOPSY"
	 OrderType.create category: "Lab Test",  description: "MMA (METHOMELONIC ACID QUANT)"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "MOLECULAR GENETCS TESTING (SEE LIST BELOW) APO E"
	 OrderType.create category: "Lab Test",  description: "DNA FRAG X FACTOR V L MTHFR"
	 OrderType.create category: "Lab Test",  description: "PT GENE"
	 OrderType.create category: "Lab Test",  description: "PWS/AS"
	 OrderType.create category: "Lab Test",  description: "MONONUCLEOSIS TEST"
	 OrderType.create category: "Lab Test",  description: "MOTOR SENSORY NEUROPATHY"
	 OrderType.create category: "Lab Test",  description: "MPS SPOT TEST"
	 OrderType.create category: "Lab Test",  description: "MUCOPOLYSACCHARIDES QUAL - URINE"
	 OrderType.create category: "Lab Test",  description: "MULTIPLE SCLEROSIS PROFILE, CSF"
	 OrderType.create category: "Lab Test",  description: "MUMPS AB, IGG"
	 OrderType.create category: "Lab Test",  description: "MYCOPLASMA ANTIBODY; IGG AND/OR IGM"
	 OrderType.create category: "Lab Test",  description: "MYELIN BASIC PROTEIN"
	 OrderType.create category: "Lab Test",  description: "MYOCARDIAL AB"
	 OrderType.create category: "Lab Test",  description: "MYOGLOBIN QUANT, SERUM"
	 OrderType.create category: "Lab Test",  description: "MYOGLOBIN, URINE"
	 OrderType.create category: "Lab Test",  description: "MYSOLINE (PRIMIDONE)"
	 OrderType.create category: "Lab Test",  description: "NERVE BIOPSY"
	 OrderType.create category: "Lab Test",  description: "NETILMICIN LEVEL, SERUM"
	 OrderType.create category: "Lab Test",  description: "NEURONAL IGG AB"
	 OrderType.create category: "Lab Test",  description: "NEURONAL NUCLEAR AB"
	 OrderType.create category: "Lab Test",  description: "NEURONAL NUCLEAR AB, CSF"
	 OrderType.create category: "Lab Test",  description: "NEURON -SPECIFIC ENOLASE"
	 OrderType.create category: "Lab Test",  description: "NEURONTIN"
	 OrderType.create category: "Lab Test",  description: "NEUTROPHIL AB"
	 OrderType.create category: "Lab Test",  description: "NEUTROPHIL OXIDATIVE BURST ASSAY"
	 OrderType.create category: "Lab Test",  description: "NEWBORN SCREEN - INITIAL; CAH, GALACTOSEMIA, HEMOGLOBINAPATHY, HOMOSYSTINURIA, HYPOTHYROIDISM, MAPLE SYRUP URINE DISEASE, PHENYLKETONURIA"
	 OrderType.create category: "Lab Test",  description: "NEWBORN SCREEN - SECOND; CAH, GALACTOSEMIA, HEMOGLOBINAPATHY, HOMOSYSTINURIA, HYPOTHYROIDISM, MAPLE SYRUP URINE DISEASE, PHENYLKETONURIA"
	 OrderType.create category: "Lab Test",  description: "NITROBLUE TETRAZOLIUM DYE TEST"
	 OrderType.create category: "Lab Test",  description: "NORPACE, QUANT SERUM (DISOPYRAMIDE)"
	 OrderType.create category: "Lab Test",  description: "NORTRIPTYLINE"
	 OrderType.create category: "Lab Test",  description: "OBSTETRIC PANEL; CBC, HEPATITIS B SURFACE AG, RUBELLA IGG, RPR, TYPE AND SCREEN"
	 OrderType.create category: "Lab Test",  description: "OCCULT BLOOD, FECES"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "OCCULT BLOOD, GASTRIC"
	 OrderType.create category: "Lab Test",  description: "OLIGOCLONAL BANDING"
	 OrderType.create category: "Lab Test",  description: "ORGANIC ACIDS, QUAL"
	 OrderType.create category: "Lab Test",  description: "ORGANIC ACIDS, QUANT"
	 OrderType.create category: "Lab Test",  description: "OSMOLALITY, SERUM"
	 OrderType.create category: "Lab Test",  description: "OSMOLALITY, URINE"
	 OrderType.create category: "Lab Test",  description: "OSMOTIC FRAGILITY; INCUBATED/UNINCUBATED"
	 OrderType.create category: "Lab Test",  description: "OSTEOCALCIN"
	 OrderType.create category: "Lab Test",  description: "OVA AND PARASITES"
	 OrderType.create category: "Lab Test",  description: "OVARY AB IGG"
	 OrderType.create category: "Lab Test",  description: "OXALATES, URINE"
	 OrderType.create category: "Lab Test",  description: "PAP SMEAR"
	 OrderType.create category: "Lab Test",  description: "PARA INFLUENZA AB - CF; PARAINFLUENZA TYPES 1,2 AND 3"
	 OrderType.create category: "Lab Test",  description: "PARACENTESIS - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "PARATHYROID HORMONE INTACT (IPTH)"
	 OrderType.create category: "Lab Test",  description: "PARATHYROID HORMONE INTACT (IPTH);"
	 OrderType.create category: "Lab Test",  description: "INTRAOPERATIVE"
	 OrderType.create category: "Lab Test",  description: "PARIETAL CELL AB, IGG"
	 OrderType.create category: "Lab Test",  description: "PARVOVIRUS B19 AB. IGG/IGM"
	 OrderType.create category: "Lab Test",  description: "PEDIATRIC ALLERGY TEST 1; EGG WHITE, MILK, WHEAT, OAT, SOYBEAN"
	 OrderType.create category: "Lab Test",  description: "PEDIATRIC ALLERGY TEST 2; D.FARINAE, D.PTERNYSSINUS, DOG EPITHELIUM, CAT EPITHELIUM, ALTERNARIA ENIUS, EGG WHITE, MILK, WHEAT, CORN, SOYBEAN, HOUSE DUST GREER"
	 OrderType.create category: "Lab Test",  description: "PEMPHIGOID AB (EPIDERMAL)"
	 OrderType.create category: "Lab Test",  description: "PENTOBARBITOL"
	 OrderType.create category: "Lab Test",  description: "PERICARDIAL FLUID - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "PERINUCLEAR FACTOR AB"
	 OrderType.create category: "Lab Test",  description: "PERIDONEAL WASHING - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "PERTUSSIS CULTURE"
	 OrderType.create category: "Lab Test",  description: "PERTUSSIS FA STAIN; SEE MICROBIOLOGY SECTION"
	 OrderType.create category: "Lab Test",  description: "PH, FECAL"
	 OrderType.create category: "Lab Test",  description: "PH, URINE"
	 OrderType.create category: "Lab Test",  description: "PH - OTHER"
	 OrderType.create category: "Lab Test",  description: "PHENOBARBITAL"
	 OrderType.create category: "Lab Test",  description: "PHENYLALANINE, QUANT"
	 OrderType.create category: "Lab Test",  description: "PHENYTOIN (DILANTIN)"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "PHENYTOIN FREE; QUANT"
	 OrderType.create category: "Lab Test",  description: "PHOSPHATASE, ALKALINE; ISOENZYME"
	 OrderType.create category: "Lab Test",  description: "PHOSPHORUS, SERUM"
	 OrderType.create category: "Lab Test",  description: "PHOSPHORUS, 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "PHOSPHORUS, RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "PHYTANIC ACID"
	 OrderType.create category: "Lab Test",  description: "PINWORM TAPE PREP"
	 OrderType.create category: "Lab Test",  description: "PKU (PHENYLALANINE, QUANT)"
	 OrderType.create category: "Lab Test",  description: "PLASMA HEMOGLOBIN"
	 OrderType.create category: "Lab Test",  description: "PLASMINOGEN"
	 OrderType.create category: "Lab Test",  description: "PLATELET AB - DIRECT"
	 OrderType.create category: "Lab Test",  description: "PLATELET AB - INDIRECT"
	 OrderType.create category: "Lab Test",  description: "PLATELET AGGREGGATE"
	 OrderType.create category: "Lab Test",  description: "PLATELET COUNT - HEMOGRAM"
	 OrderType.create category: "Lab Test",  description: "PLATELET FACTOR (PF-4) AB"
	 OrderType.create category: "Lab Test",  description: "PLAVIX"
	 OrderType.create category: "Lab Test",  description: "PLEURAL FLUID - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "PNEUMOCYSTIS DFA"
	 OrderType.create category: "Lab Test",  description: "POLIO SEROTYPE; POLIO TYPES 1, 2, AND 3"
	 OrderType.create category: "Lab Test",  description: "PORPHOBILINOGEN DEAMINASE (URO1"
	 OrderType.create category: "Lab Test",  description: "SYNTHETASE)"
	 OrderType.create category: "Lab Test",  description: "PORPHOBILINOGEN, QUALITATIVE"
	 OrderType.create category: "Lab Test",  description: "PORPHOBILINOGEN, QUANTITATIVE"
	 OrderType.create category: "Lab Test",  description: "PORPHYRINS, URINE QUANTITATIVE; COPROPORPHYRIN, UROPORPHYRIN"
	 OrderType.create category: "Lab Test",  description: "POTASSIUM"
	 OrderType.create category: "Lab Test",  description: "POTASSIUM, FLUID"
	 OrderType.create category: "Lab Test",  description: "POTASSIUM, RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "POTASSIUM, 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "PRE-ALBUMIN LEVEL"
	 OrderType.create category: "Lab Test",  description: "PREGNANCY, QUALITATIVE"
	 OrderType.create category: "Lab Test",  description: "PREGNANCY, QUALITATIVE"
	 OrderType.create category: "Lab Test",  description: "PREGNANETRIOL, URINE"
	 OrderType.create category: "Lab Test",  description: "PRIMIDONE"
	 OrderType.create category: "Lab Test",  description: "PROCAINAMIDE; NAPA"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "PROCALCITONIN ASSAY (PCT)"
	 OrderType.create category: "Lab Test",  description: "PROGESTERONE"
	 OrderType.create category: "Lab Test",  description: "PROGRAF (TACROLIMUS)"
	 OrderType.create category: "Lab Test",  description: "PROINSULIN"
	 OrderType.create category: "Lab Test",  description: "PROLACTIN"
	 OrderType.create category: "Lab Test",  description: "PROPOXYPHENE"
	 OrderType.create category: "Lab Test",  description: "PROPRANOLOL"
	 OrderType.create category: "Lab Test",  description: "PROSTATE SPECIFIC ANTIGEN  (PSA)"
	 OrderType.create category: "Lab Test",  description: "PROSTATIC ACID PHOSPHATASE"
	 OrderType.create category: "Lab Test",  description: "PROTEIN ELECTROPHORESIS; 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "PROTEIN ELECTROPHORESIS- CSF; ALBUMIN, ALPHA-2, BETA, GAMMA, PRE-ALBUMIN, TOTAL PROTEIN"
	 OrderType.create category: "Lab Test",  description: "PROTEIN ELECTROPHORESIS- SERUM; ALBUMIN, ALPHA-1, ALPHA-2, BETA, GAMMA, TOTAL PROTEIN"
	 OrderType.create category: "Lab Test",  description: "PROTEIN - C  FUNCTIONAL"
	 OrderType.create category: "Lab Test",  description: "PROTEIN - S, FUNCTIONAL"
	 OrderType.create category: "Lab Test",  description: "PROTEIN; TOTAL"
	 OrderType.create category: "Lab Test",  description: "PROTEIN, TOTAL BODY FLUID"
	 OrderType.create category: "Lab Test",  description: "PROTEIN, TOTAL CSF"
	 OrderType.create category: "Lab Test",  description: "PROTEIN, TOTAL 24HR URINE"
	 OrderType.create category: "Lab Test",  description: "PROTEIN, TOTAL 12HR URINE"
	 OrderType.create category: "Lab Test",  description: "PROTEIN, TOTAL RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "PROTHROMBIN GENE/PCR"
	 OrderType.create category: "Lab Test",  description: "PROTHROMBIN TIME (PT)"
	 OrderType.create category: "Lab Test",  description: "PROTRIPTYLINE"
	 OrderType.create category: "Lab Test",  description: "PROZAC (FLUOXETINE)"
	 OrderType.create category: "Lab Test",  description: "PSA (PROSTATE SPECIFIC ANTIGEN)"
	 OrderType.create category: "Lab Test",  description: "PSEUDOCHOLINESTERASE"
	 OrderType.create category: "Lab Test",  description: "PT (PROTHROMBIN TIME)"
	 OrderType.create category: "Lab Test",  description: "PT MIXING STUDY SCREEN-QUAL"
	 OrderType.create category: "Lab Test",  description: "PTH, INTACT TERMINAL"
	 OrderType.create category: "Lab Test",  description: "PTT"
	 OrderType.create category: "Lab Test",  description: "PTT MIXING STUDY SCREEN (INHIBITOR STUDY)"
	 OrderType.create category: "Lab Test",  description: "PURKINJI CELL"
	 OrderType.create category: "Lab Test",  description: "PYRUVATE (PYRUVIC ACID)"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "PYRUVATE, CSF"
	 OrderType.create category: "Lab Test",  description: "Q FEVER ANTIBODIES"
	 OrderType.create category: "Lab Test",  description: "QUANTIFERON TB GOLD"
	 OrderType.create category: "Lab Test",  description: "QUINIDINE"
	 OrderType.create category: "Lab Test",  description: "RAPID HIV"
	 OrderType.create category: "Lab Test",  description: "RAJI CELL ASSAY"
	 OrderType.create category: "Lab Test",  description: "RAPID STREP THROAT"
	 OrderType.create category: "Lab Test",  description: "RAST-LATEX ALLERGY IGE"
	 OrderType.create category: "Lab Test",  description: "RBC CHOLINESTERASE"
	 OrderType.create category: "Lab Test",  description: "RBC FOLATE"
	 OrderType.create category: "Lab Test",  description: "REDUCING SUBSTANCE"
	 OrderType.create category: "Lab Test",  description: "RENAL BIOPSY"
	 OrderType.create category: "Lab Test",  description: "RENAL FUNCTION PANEL"
	 OrderType.create category: "Lab Test",  description: "RENIN"
	 OrderType.create category: "Lab Test",  description: "RESPIRATORY CULTURE"
	 OrderType.create category: "Lab Test",  description: "RESPIRATORY CULTURE + GRAM"
	 OrderType.create category: "Lab Test",  description: "RESP SYNCYTIAL VIRUS AB"
	 OrderType.create category: "Lab Test",  description: "RETICULOCYTE COUNT"
	 OrderType.create category: "Lab Test",  description: "REVERSE T3"
	 OrderType.create category: "Lab Test",  description: "RF (RHEUMATOID FACTOR)"
	 OrderType.create category: "Lab Test",  description: "RH NEGATIVE  WORKUP; ABO, RH, FETAL SCREEN- FMH, INDIRECT ANTIGLOBIN"
	 OrderType.create category: "Lab Test",  description: "RHEUMATOID FACTOR"
	 OrderType.create category: "Lab Test",  description: "RIBOSOMAL P PROTEIN IGG"
	 OrderType.create category: "Lab Test",  description: "ROCKY MOUNTAIN SPOTTED FEVER"
	 OrderType.create category: "Lab Test",  description: "ROTAVIRUS"
	 OrderType.create category: "Lab Test",  description: "RPR (SYPHILIS) SCREEN"
	 OrderType.create category: "Lab Test",  description: "RSV AB"
	 OrderType.create category: "Lab Test",  description: "RSV - DFA; (RESPIRATORY SYNCYTIAL VIRUS ANTIBODY)"
	 OrderType.create category: "Lab Test",  description: "RUBELLA AB IgM"
	 OrderType.create category: "Lab Test",  description: "RUBELLA SCREEN, IGG"
	 OrderType.create category: "Lab Test",  description: "RUBEOLA (MEASLES) AB IGM"
	 OrderType.create category: "Lab Test",  description: "RUBEOLA (MEASLES) AB,IGG"
	 OrderType.create category: "Lab Test",  description: "SALICYLATE"
	 OrderType.create category: "Lab Test",  description: "SARS"
	 OrderType.create category: "Lab Test",  description: "SCABIES PREP"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "SCHLICTER TEST; SEE SERUM-CIDAL TEST"
	 OrderType.create category: "Lab Test",  description: "SEDIMENTATION RATE (WESTERGREN)"
	 OrderType.create category: "Lab Test",  description: "SEROTONIN, SERUM"
	 OrderType.create category: "Lab Test",  description: "SEROTONIN, URINE"
	 OrderType.create category: "Lab Test",  description: "SEROTONIN, WHOLE BLOOD"
	 OrderType.create category: "Lab Test",  description: "SERUM CIDAL PEAK"
	 OrderType.create category: "Lab Test",  description: "SERUM CIDAL TROUGH"
	 OrderType.create category: "Lab Test",  description: "SERUM FOLATE"
	 OrderType.create category: "Lab Test",  description: "SGOT (AST)"
	 OrderType.create category: "Lab Test",  description: "SGOT, CSF"
	 OrderType.create category: "Lab Test",  description: "SGOT , FLUID"
	 OrderType.create category: "Lab Test",  description: "SGPT (ALT)"
	 OrderType.create category: "Lab Test",  description: "SIALIC ACID - LIPID ASSOC (LASA)"
	 OrderType.create category: "Lab Test",  description: "SICKLE CELL"
	 OrderType.create category: "Lab Test",  description: "SINEQUAN (DOXEPIN)"
	 OrderType.create category: "Lab Test",  description: "SJOGRENS AB"
	 OrderType.create category: "Lab Test",  description: "SKELETAL MUSCLE ANTIBODY"
	 OrderType.create category: "Lab Test",  description: "SKIN LESION SCRAPE - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "SMEAR - EOS"
	 OrderType.create category: "Lab Test",  description: "SMEAR - PATHOLOGY"
	 OrderType.create category: "Lab Test",  description: "SMEAR - POLYS"
	 OrderType.create category: "Lab Test",  description: "SMITH SMOOTH MUSCLE AB"
	 OrderType.create category: "Lab Test",  description: "SMOOTH MUSCLE AB"
	 OrderType.create category: "Lab Test",  description: "SODIUM"
	 OrderType.create category: "Lab Test",  description: "SODIUM, FLUID"
	 OrderType.create category: "Lab Test",  description: "SODIUM, RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "SODIUM, 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "SOMATAMEDIN C; (INSULIN LIKE GROWTH FACTOR I)"
	 OrderType.create category: "Lab Test",  description: "SPERM AB IGG"
	 OrderType.create category: "Lab Test",  description: "SPERM - POST VASECTOMY"
	 OrderType.create category: "Lab Test",  description: "SPUTUM - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "SSA AND SSB; (SJOGREN'S PANEL)"
	 OrderType.create category: "Lab Test",  description: "ST. LOUIS ENCEPHALITIS AB"
	 OrderType.create category: "Lab Test",  description: "STEM CELL ASSAY"
	 OrderType.create category: "Lab Test",  description: "STONE ANALYSIS"
	 OrderType.create category: "Lab Test",  description: "STOOL CULTURE; (INCL SALOMELLA, SHIGELLA, CAMPYLOBACTER)"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "STREP SCREEN"
	 OrderType.create category: "Lab Test",  description: "STREPTOLYSIN O AB"
	 OrderType.create category: "Lab Test",  description: "STREPTOZYME"
	 OrderType.create category: "Lab Test",  description: "STRIATED MUSCLE AB, IGG"
	 OrderType.create category: "Lab Test",  description: "STRONGYLOIDES IGG"
	 OrderType.create category: "Lab Test",  description: "SUDAN BLACK"
	 OrderType.create category: "Lab Test",  description: "SUGAR WATER TEST"
	 OrderType.create category: "Lab Test",  description: "SULFADIAZINE (SULFONANIDES)"
	 OrderType.create category: "Lab Test",  description: "SWEAT CHLORIDE"
	 OrderType.create category: "Lab Test",  description: "SYNOVIAL FLUID; CRYSTALS"
	 OrderType.create category: "Lab Test",  description: "SYNOVIAL FLUID; MUCIN CLOT, VISCOSITY"
	 OrderType.create category: "Lab Test",  description: "SYPHILIS ANTIBODY"
	 OrderType.create category: "Lab Test",  description: "SYPHILIS SCREEN - CSF (VDRL)"
	 OrderType.create category: "Lab Test",  description: "SYPHILIS SCREEN - RPR"
	 OrderType.create category: "Lab Test",  description: "T3; (TRIIODOTHYRONINE, TOTAL)"
	 OrderType.create category: "Lab Test",  description: "T3, FREE (TRIIODOTHYRONINE)"
	 OrderType.create category: "Lab Test",  description: "T3, REVERSE"
	 OrderType.create category: "Lab Test",  description: "T3, UPTAKE (RESIN UPTAKE)"
	 OrderType.create category: "Lab Test",  description: "T4; (THYROXINE)"
	 OrderType.create category: "Lab Test",  description: "T4, FREE (THYROXINE; FREE)"
	 OrderType.create category: "Lab Test",  description: "T CELL LYMPHOCYTE PHENOTYPING (CD4/CD8)"
	 OrderType.create category: "Lab Test",  description: "TACROLIMUS (FK506)"
	 OrderType.create category: "Lab Test",  description: "TAY-SACHS"
	 OrderType.create category: "Lab Test",  description: "TEGRETOL; (CARBAMAZEPINE)"
	 OrderType.create category: "Lab Test",  description: "TEICHOIC ACID ANTIBODIES"
	 OrderType.create category: "Lab Test",  description: "TEMAZEPAM"
	 OrderType.create category: "Lab Test",  description: "TESTOSTERONE FREE"
	 OrderType.create category: "Lab Test",  description: "TESTOSTERONE TOTAL"
	 OrderType.create category: "Lab Test",  description: "TETANUS TITER - IGG"
	 OrderType.create category: "Lab Test",  description: "THEOPHYLLINE"
	 OrderType.create category: "Lab Test",  description: "THIAMINE (VITAMIN B1)"
	 OrderType.create category: "Lab Test",  description: "THIOCYANATE"
	 OrderType.create category: "Lab Test",  description: "THIORIDAZINE/MESORIDAZIN"
	 OrderType.create category: "Lab Test",  description: "THIOTHIXENE"
	 OrderType.create category: "Lab Test",  description: "THROAT CULTURE"
	 OrderType.create category: "Lab Test",  description: "THROMBIN TIME (TCT)"
	 OrderType.create category: "Lab Test",  description: "THYROGLOBIN; iNCL THYROGLOCULIN AB AND % THYROGLOBUIN RECOVERED"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "THYROGLOBULIN AB"
	 OrderType.create category: "Lab Test",  description: "THYROID AB; INCL TPO AB AND THYROGLOBULIN AB"
	 OrderType.create category: "Lab Test",  description: "THYROID GROWTH STIM HORMONE RECEPTOR AB"
	 OrderType.create category: "Lab Test",  description: "THYROID STIMULATING IMMUNOGLOBULIN (TSI)"
	 OrderType.create category: "Lab Test",  description: "THYROID STIMULATING HORMONE (TSH)"
	 OrderType.create category: "Lab Test",  description: "THYROXINE (T4)"
	 OrderType.create category: "Lab Test",  description: "THYROXINE BINDING GLOBULIN (TBG)"
	 OrderType.create category: "Lab Test",  description: "THYROXINE FREE (FREE T4)"
	 OrderType.create category: "Lab Test",  description: "TISSUE CULT + GRAM + ANAEROBE"
	 OrderType.create category: "Lab Test",  description: "TISSUE SPECIMEN GROSS ONLY"
	 OrderType.create category: "Lab Test",  description: "TOBRAMYCIN"
	 OrderType.create category: "Lab Test",  description: "TOCAINIDE"
	 OrderType.create category: "Lab Test",  description: "TOLUENE"
	 OrderType.create category: "Lab Test",  description: "TOPIRAMATE"
	 OrderType.create category: "Lab Test",  description: "TOTAL BILIRUBIN; INCLUDES CONJUGATED BILIRUBIN"
	 OrderType.create category: "Lab Test",  description: "TOTAL PROTEIN"
	 OrderType.create category: "Lab Test",  description: "TOTAL PROTEIN -  CSF"
	 OrderType.create category: "Lab Test",  description: "TOTAL PROTEIN - FLUID"
	 OrderType.create category: "Lab Test",  description: "TOTAL PROTEIN - RANDOM"
	 OrderType.create category: "Lab Test",  description: "TOTAL PROTEIN - 12 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "TOTAL PROTEIN - 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "TOXOPLASMA - IgG"
	 OrderType.create category: "Lab Test",  description: "TOXOPLASMA -  IgM"
	 OrderType.create category: "Lab Test",  description: "TRANSFERRIN"
	 OrderType.create category: "Lab Test",  description: "TRANSFUSION RXN"
	 OrderType.create category: "Lab Test",  description: "TRAXENE; (CLORAZEPATE OR NORDIAZEPAM)"
	 OrderType.create category: "Lab Test",  description: "TRAUMA LAVAGE; BILE, RBC, FOOD PARTICLES, GRAM STAIN, NUCLEATED CELLS"
	 OrderType.create category: "Lab Test",  description: "TRAZODONE"
	 OrderType.create category: "Lab Test",  description: "TRICHINELLA SPIRILLS"
	 OrderType.create category: "Lab Test",  description: "TRICYCLIC ANTIDEPRESSANT-SERUM"
	 OrderType.create category: "Lab Test",  description: "TRIGLYCERIDES"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "TROPONIN I"
	 OrderType.create category: "Lab Test",  description: "TSH (THYROID STIMULATING HORMONE)"
	 OrderType.create category: "Lab Test",  description: "TSI (THYROID STIM IMMUNOGLOBULIN)"
	 OrderType.create category: "Lab Test",  description: "TYPE - ABO AND RH"
	 OrderType.create category: "Lab Test",  description: "TYPE AND CROSSMATCH; ABO, CROSSMATCH, INDIRECT ANTIGLOBIN, RH"
	 OrderType.create category: "Lab Test",  description: "TYPE AND SCREEN; ABO, INDIRECT ANTIGLOBULIN, RH"
	 OrderType.create category: "Lab Test",  description: "TYPHUS FEVER AB IGG/IGM"
	 OrderType.create category: "Lab Test",  description: "TZANCK/HERPES"
	 OrderType.create category: "Lab Test",  description: "ULTRACENTRIFUGED SPECIMEN"
	 OrderType.create category: "Lab Test",  description: "URIC ACID"
	 OrderType.create category: "Lab Test",  description: "URIC ACID - 24 HOUR URINE"
	 OrderType.create category: "Lab Test",  description: "URIC ACID - RANDOM URINE"
	 OrderType.create category: "Lab Test",  description: "URINALYSIS"
	 OrderType.create category: "Lab Test",  description: "URINARY EOSINOPILS"
	 OrderType.create category: "Lab Test",  description: "URINE - CYTOLOGY"
	 OrderType.create category: "Lab Test",  description: "URINE CULTURE"
	 OrderType.create category: "Lab Test",  description: "URINE CYSTINE SCREEN"
	 OrderType.create category: "Lab Test",  description: "URINE ORGANIC ACIDS"
	 OrderType.create category: "Lab Test",  description: "URINE UREA NITROGEN, RANDOM"
	 OrderType.create category: "Lab Test",  description: "URINE UREA NITROGEN, 24 HOUR"
	 OrderType.create category: "Lab Test",  description: "URO - 1   - SYNTHETASE (PORPHOBILINOGEN DEAMINASE)"
	 OrderType.create category: "Lab Test",  description: "UROBILINOGEN QUANT"
	 OrderType.create category: "Lab Test",  description: "VALPROIC ACID"
	 OrderType.create category: "Lab Test",  description: "VANCOMYCIN"
	 OrderType.create category: "Lab Test",  description: "VARICELLA AB, IGG AND/OR IGM"
	 OrderType.create category: "Lab Test",  description: "VARICELLA ZOSTER AB, IGG"
	 OrderType.create category: "Lab Test",  description: "VARICELLA ZOSTER AB, IGG/IGM"
	 OrderType.create category: "Lab Test",  description: "VARICELLA ZOSTER AB, IGM"
	 OrderType.create category: "Lab Test",  description: "VARICELLA ZOSTER BY PCR, CSF"
	 OrderType.create category: "Lab Test",  description: "VASOACTIVE INTESTINAL PEPTIDE"
	 OrderType.create category: "Lab Test",  description: "VASOPRESSIN, (ADH)"
	 OrderType.create category: "Lab Test",  description: "VDRL - CSF (SYPHILIS SCREEN)"
	 OrderType.create category: "Lab Test",  description: "VERAPAMIL"
	 OrderType.create category: "Lab Test",  description: "VIBRIO CULTURE"
	 OrderType.create category: "Lab Test",  description: "TEST"
	 OrderType.create category: "Lab Test",  description: "VIRAL CULTURE"
	 OrderType.create category: "Lab Test",  description: "VIRAL CULTURE -  BLOOD"
	 OrderType.create category: "Lab Test",  description: "VIRAL  RESPIRATORY CULTURE  - DFA;"
	 OrderType.create category: "Lab Test",  description: "ADENOVIRUS, INFLUENZA A AND B, PARAINFLUENZA 1,"
	 OrderType.create category: "Lab Test",  description: "2 AND 3"
	 OrderType.create category: "Lab Test",  description: "VISCOSITY"
	 OrderType.create category: "Lab Test",  description: "VITAMIN A"
	 OrderType.create category: "Lab Test",  description: "VITAMIN B1 (THIAMIN)"
	 OrderType.create category: "Lab Test",  description: "VITAMIN B-6 (PYRIDOXAL PHOS)"
	 OrderType.create category: "Lab Test",  description: "VITAMIN B-12"
	 OrderType.create category: "Lab Test",  description: "VITAMIN C"
	 OrderType.create category: "Lab Test",  description: "VITAMIN D TOTAL (D2 AND D3)"
	 OrderType.create category: "Lab Test",  description: "VITAMIN D, 1,  25 - DIHYDROXY"
	 OrderType.create category: "Lab Test",  description: "VITAMIN E (TOCOPHEROL ALPHA)"
	 OrderType.create category: "Lab Test",  description: "VLDL - VERY LOW DENSITY LIPOPROTEIN"
	 OrderType.create category: "Lab Test",  description: "VMA - URINE; HOMOVANILLIC ACID"
	 OrderType.create category: "Lab Test",  description: "VON WILLEBRAND FACTOR AG RISTOCETIN CO- FACTOR"
	 OrderType.create category: "Lab Test",  description: "VRE SCREEN"
	 OrderType.create category: "Lab Test",  description: "WESTERN BLOT"
	 OrderType.create category: "Lab Test",  description: "WEST NILE VIRUS"
	 OrderType.create category: "Lab Test",  description: "WET MOUNT - CLUE CELLS"
	 OrderType.create category: "Lab Test",  description: "WET MOUNT - FUNGUS"
	 OrderType.create category: "Lab Test",  description: "WET MOUNT - TRICHOMONAS"
	 OrderType.create category: "Lab Test",  description: "WET MOUNT -  YEAST"
	 OrderType.create category: "Lab Test",  description: "WOUND CULTURE + GRAM"
	 OrderType.create category: "Lab Test",  description: "WOUND CULTURE + GRAM + ANAEROBE"
	 OrderType.create category: "Lab Test",  description: "XYLOSE ABSORPTION"
	 OrderType.create category: "Lab Test",  description: "YELLOW FEVER AB (ST. LOUIS ENCEPHALITIS)"
	 OrderType.create category: "Lab Test",  description: "YERSINIA  AB; YERSINIA E, TYPES 3, 8 AND 9, YERSINIA P"
	 OrderType.create category: "Lab Test",  description: "YERSINIA CULTURE STOOL"
	 OrderType.create category: "Lab Test",  description: "YO (PURKINJE CELL)"
	 OrderType.create category: "Lab Test",  description: "ZARONTIN  (ETHOSUXIMIDE)"
	 OrderType.create category: "Lab Test",  description: "ZINC"
	 OrderType.create category: "Lab Test",  description: "ZINC PROTOPORPHYRIN"
	 OrderType.create category: "Cardiology", description: "EKG, 12-LEAD"
	 OrderType.create category: "Cardiology", description: "HOLTER MONITORING"
	 OrderType.create category: "Cardiology", description: "ECHOCARDIOGRAM"
	 OrderType.create category: "Cardiology", description: "EXERCISE STRESS TEST"
	 OrderType.create category: "Cardiology", description: "SEGMENTAL DOPPLER PRESSURES OF THE LEGS"
	 OrderType.create category: "Cardiology", description: "CARDIAC CATHETERIZATION"
	 OrderType.create category: "Radiology", description: "X-RAY (PLEASE SPECIFY IN NOTE)"
	 OrderType.create category: "Radiology", description: "CT SCAN (PLEASE SPECIFY IN NOTE)"
	 OrderType.create category: "Radiology", description: "MRI (PLEASE SPECIFY IN NOTE)"
	 OrderType.create category: "Radiology", description: "ULTRASOUND (PLEASE SPECIFY IN NOTE)"	
  end

  def down
  end
end
