require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LabReportTemplatesController do

  # This should return the minimal set of attributes required to create a valid
  # LabReportTemplate. As you add validations to LabReportTemplate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LabReportTemplatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lab_report_templates as @lab_report_templates" do
      lab_report_template = LabReportTemplate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lab_report_templates).should eq([lab_report_template])
    end
  end

  describe "GET show" do
    it "assigns the requested lab_report_template as @lab_report_template" do
      lab_report_template = LabReportTemplate.create! valid_attributes
      get :show, {:id => lab_report_template.to_param}, valid_session
      assigns(:lab_report_template).should eq(lab_report_template)
    end
  end

  describe "GET new" do
    it "assigns a new lab_report_template as @lab_report_template" do
      get :new, {}, valid_session
      assigns(:lab_report_template).should be_a_new(LabReportTemplate)
    end
  end

  describe "GET edit" do
    it "assigns the requested lab_report_template as @lab_report_template" do
      lab_report_template = LabReportTemplate.create! valid_attributes
      get :edit, {:id => lab_report_template.to_param}, valid_session
      assigns(:lab_report_template).should eq(lab_report_template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LabReportTemplate" do
        expect {
          post :create, {:lab_report_template => valid_attributes}, valid_session
        }.to change(LabReportTemplate, :count).by(1)
      end

      it "assigns a newly created lab_report_template as @lab_report_template" do
        post :create, {:lab_report_template => valid_attributes}, valid_session
        assigns(:lab_report_template).should be_a(LabReportTemplate)
        assigns(:lab_report_template).should be_persisted
      end

      it "redirects to the created lab_report_template" do
        post :create, {:lab_report_template => valid_attributes}, valid_session
        response.should redirect_to(LabReportTemplate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lab_report_template as @lab_report_template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LabReportTemplate.any_instance.stub(:save).and_return(false)
        post :create, {:lab_report_template => {}}, valid_session
        assigns(:lab_report_template).should be_a_new(LabReportTemplate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LabReportTemplate.any_instance.stub(:save).and_return(false)
        post :create, {:lab_report_template => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lab_report_template" do
        lab_report_template = LabReportTemplate.create! valid_attributes
        # Assuming there are no other lab_report_templates in the database, this
        # specifies that the LabReportTemplate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LabReportTemplate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lab_report_template.to_param, :lab_report_template => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lab_report_template as @lab_report_template" do
        lab_report_template = LabReportTemplate.create! valid_attributes
        put :update, {:id => lab_report_template.to_param, :lab_report_template => valid_attributes}, valid_session
        assigns(:lab_report_template).should eq(lab_report_template)
      end

      it "redirects to the lab_report_template" do
        lab_report_template = LabReportTemplate.create! valid_attributes
        put :update, {:id => lab_report_template.to_param, :lab_report_template => valid_attributes}, valid_session
        response.should redirect_to(lab_report_template)
      end
    end

    describe "with invalid params" do
      it "assigns the lab_report_template as @lab_report_template" do
        lab_report_template = LabReportTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LabReportTemplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => lab_report_template.to_param, :lab_report_template => {}}, valid_session
        assigns(:lab_report_template).should eq(lab_report_template)
      end

      it "re-renders the 'edit' template" do
        lab_report_template = LabReportTemplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LabReportTemplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => lab_report_template.to_param, :lab_report_template => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lab_report_template" do
      lab_report_template = LabReportTemplate.create! valid_attributes
      expect {
        delete :destroy, {:id => lab_report_template.to_param}, valid_session
      }.to change(LabReportTemplate, :count).by(-1)
    end

    it "redirects to the lab_report_templates list" do
      lab_report_template = LabReportTemplate.create! valid_attributes
      delete :destroy, {:id => lab_report_template.to_param}, valid_session
      response.should redirect_to(lab_report_templates_url)
    end
  end

end
