require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecentActivitiesController do

  # This should return the minimal set of attributes required to create a valid
  # RecentActivity. As you add validations to RecentActivity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecentActivitiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all recent_activities as @recent_activities" do
      recent_activity = RecentActivity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recent_activities).should eq([recent_activity])
    end
  end

  describe "GET show" do
    it "assigns the requested recent_activity as @recent_activity" do
      recent_activity = RecentActivity.create! valid_attributes
      get :show, {:id => recent_activity.to_param}, valid_session
      assigns(:recent_activity).should eq(recent_activity)
    end
  end

  describe "GET new" do
    it "assigns a new recent_activity as @recent_activity" do
      get :new, {}, valid_session
      assigns(:recent_activity).should be_a_new(RecentActivity)
    end
  end

  describe "GET edit" do
    it "assigns the requested recent_activity as @recent_activity" do
      recent_activity = RecentActivity.create! valid_attributes
      get :edit, {:id => recent_activity.to_param}, valid_session
      assigns(:recent_activity).should eq(recent_activity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecentActivity" do
        expect {
          post :create, {:recent_activity => valid_attributes}, valid_session
        }.to change(RecentActivity, :count).by(1)
      end

      it "assigns a newly created recent_activity as @recent_activity" do
        post :create, {:recent_activity => valid_attributes}, valid_session
        assigns(:recent_activity).should be_a(RecentActivity)
        assigns(:recent_activity).should be_persisted
      end

      it "redirects to the created recent_activity" do
        post :create, {:recent_activity => valid_attributes}, valid_session
        response.should redirect_to(RecentActivity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recent_activity as @recent_activity" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecentActivity.any_instance.stub(:save).and_return(false)
        post :create, {:recent_activity => {}}, valid_session
        assigns(:recent_activity).should be_a_new(RecentActivity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecentActivity.any_instance.stub(:save).and_return(false)
        post :create, {:recent_activity => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recent_activity" do
        recent_activity = RecentActivity.create! valid_attributes
        # Assuming there are no other recent_activities in the database, this
        # specifies that the RecentActivity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecentActivity.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => recent_activity.to_param, :recent_activity => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested recent_activity as @recent_activity" do
        recent_activity = RecentActivity.create! valid_attributes
        put :update, {:id => recent_activity.to_param, :recent_activity => valid_attributes}, valid_session
        assigns(:recent_activity).should eq(recent_activity)
      end

      it "redirects to the recent_activity" do
        recent_activity = RecentActivity.create! valid_attributes
        put :update, {:id => recent_activity.to_param, :recent_activity => valid_attributes}, valid_session
        response.should redirect_to(recent_activity)
      end
    end

    describe "with invalid params" do
      it "assigns the recent_activity as @recent_activity" do
        recent_activity = RecentActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecentActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => recent_activity.to_param, :recent_activity => {}}, valid_session
        assigns(:recent_activity).should eq(recent_activity)
      end

      it "re-renders the 'edit' template" do
        recent_activity = RecentActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecentActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => recent_activity.to_param, :recent_activity => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recent_activity" do
      recent_activity = RecentActivity.create! valid_attributes
      expect {
        delete :destroy, {:id => recent_activity.to_param}, valid_session
      }.to change(RecentActivity, :count).by(-1)
    end

    it "redirects to the recent_activities list" do
      recent_activity = RecentActivity.create! valid_attributes
      delete :destroy, {:id => recent_activity.to_param}, valid_session
      response.should redirect_to(recent_activities_url)
    end
  end

end
